# 导入主题颜色配置
# 导入主题颜色配置
import:
  - /home/flork/.config/alacritty/themes/themes/material_theme.yaml

live_config_reload: true
font:
  size: 11
  normal:
    family: JetBrainsMOnoNL Nerd Font Mono
    style: ExtraBold
  bold:
    family: VictorMono Nerd Font Mono
    style: Bold Italic
  italic:
    family: VictorMono Nerd Font Mono
    style: Bold Italic
# 设置字
window:
  opacity: 1.0
  padding:
    x: 7
    y: 7
# set startup mode
startup_mode: Fullscreen

# highlight window damage info
highlight_damage: true

# set cursor style
cursor:
  style: Beam

# bind F11 to Fullscreen
colors:
  # COLORSCHEME: base16-rose-pine-moon.yml
  # Default colors
  primary:
    background: '0x232136'
    foreground: '0xe0def4'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0x232136'
    cursor: '0xe0def4'

  # Normal colors
  normal:
    black: '0x232136'
    red: '0xecebf0'
    green: '0xea9a97'
    yellow: '0xf6c177'
    blue: '0x9ccfd8'
    magenta: '0xc4a7e7'
    cyan: '0x3e8fb0'
    white: '0xe0def4'

  # Bright colors
  bright:
    black: '0x59546d'
    red: '0xeb6f92'
    green: '0x2a273f'
    yellow: '0x393552'
    blue: '0x817c9c'
    magenta: '0xf5f5f7'
    cyan: '0xb9b9bc'
    white: '0xd9d7e1'

  indexed_colors:
    - {index: 16, color: '0xeb6f92'}
    - {index: 17, color: '0xb9b9bc'}
    - {index: 18, color: '0x2a273f'}
    - {index: 19, color: '0x393552'}
    - {index: 20, color: '0x817c9c'}
    - {index: 21, color: '0xf5f5f7'}
