# Base16 OceanicNext 256 - alacritty color config
# https://github.com/voronianski/oceanic-next-color-scheme
colors:
  # Default colors
  primary:
    background: '0x1b2b34'
    foreground: '0xc0c5ce'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0x1b2b34'
    cursor: '0xc0c5ce'

  # Normal colors
  normal:
    black:   '0x1b2b34'
    red:     '0xec5f67'
    green:   '0x99c794'
    yellow:  '0xfac863'
    blue:    '0x6699cc'
    magenta: '0xc594c5'
    cyan:    '0x5fb3b3'
    white:   '0xc0c5ce'

  # Bright colors
  bright:
    black:   '0x65737e'
    red:     '0xec5f67'
    green:   '0x99c794'
    yellow:  '0xfac863'
    blue:    '0x6699cc'
    magenta: '0xc594c5'
    cyan:    '0x5fb3b3'
    white:   '0xd8dee9'

  indexed_colors:
    - { index: 16, color: '0xf99157' }
    - { index: 17, color: '0xab7967' }
    - { index: 18, color: '0x343d46' }
    - { index: 19, color: '0x4f5b66' }
    - { index: 20, color: '0xa7adba' }
    - { index: 21, color: '0xcdd3de' }
