# Base16 selenized-black 256 - alacritty color config
# Jan Warchol (https://github.com/jan-warchol/selenized) / adapted to base16 by ali
colors:
  # Default colors
  primary:
    background: '0x181818'
    foreground: '0xb9b9b9'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0x181818'
    cursor: '0xb9b9b9'

  # Normal colors
  normal:
    black:   '0x181818'
    red:     '0xed4a46'
    green:   '0x70b433'
    yellow:  '0xdbb32d'
    blue:    '0x368aeb'
    magenta: '0xa580e2'
    cyan:    '0x3fc5b7'
    white:   '0xb9b9b9'

  # Bright colors
  bright:
    black:   '0x777777'
    red:     '0xed4a46'
    green:   '0x70b433'
    yellow:  '0xdbb32d'
    blue:    '0x368aeb'
    magenta: '0xa580e2'
    cyan:    '0x3fc5b7'
    white:   '0xdedede'

  indexed_colors:
    - { index: 16, color: '0xe67f43' }
    - { index: 17, color: '0xeb6eb7' }
    - { index: 18, color: '0x252525' }
    - { index: 19, color: '0x3b3b3b' }
    - { index: 20, color: '0x777777' }
    - { index: 21, color: '0xdedede' }
