# Base16 Flat 256 - alacritty color config
# Chris Kempson (http://chriskempson.com)
colors:
  # Default colors
  primary:
    background: '0x2c3e50'
    foreground: '0xe0e0e0'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0x2c3e50'
    cursor: '0xe0e0e0'

  # Normal colors
  normal:
    black:   '0x2c3e50'
    red:     '0xe74c3c'
    green:   '0x2ecc71'
    yellow:  '0xf1c40f'
    blue:    '0x3498db'
    magenta: '0x9b59b6'
    cyan:    '0x1abc9c'
    white:   '0xe0e0e0'

  # Bright colors
  bright:
    black:   '0x95a5a6'
    red:     '0xe74c3c'
    green:   '0x2ecc71'
    yellow:  '0xf1c40f'
    blue:    '0x3498db'
    magenta: '0x9b59b6'
    cyan:    '0x1abc9c'
    white:   '0xecf0f1'

  indexed_colors:
    - { index: 16, color: '0xe67e22' }
    - { index: 17, color: '0xbe643c' }
    - { index: 18, color: '0x34495e' }
    - { index: 19, color: '0x7f8c8d' }
    - { index: 20, color: '0xbdc3c7' }
    - { index: 21, color: '0xf5f5f5' }
