# Base16 Gruvbox Material Light, Hard - alacritty color config
# Mayush Kumar (https://github.com/MayushKumar), sainnhe (https://github.com/sainnhe/gruvbox-material-vscode)
colors:
  # Default colors
  primary:
    background: '0xf9f5d7'
    foreground: '0x654735'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0xf9f5d7'
    cursor: '0x654735'

  # Normal colors
  normal:
    black:   '0xf9f5d7'
    red:     '0xc14a4a'
    green:   '0x6c782e'
    yellow:  '0xb47109'
    blue:    '0x45707a'
    magenta: '0x945e80'
    cyan:    '0x4c7a5d'
    white:   '0x654735'

  # Bright colors
  bright:
    black:   '0xa89984'
    red:     '0xc35e0a'
    green:   '0xfbf1c7'
    yellow:  '0xe0cfa9'
    blue:    '0xc9b99a'
    magenta: '0x3c3836'
    cyan:    '0xe78a4e'
    white:   '0x282828'

draw_bold_text_with_bright_colors: false
