# Base16 Atelier Savanna - alacritty color config
# Bram de Haan (http://atelierbramdehaan.nl)
colors:
  # Default colors
  primary:
    background: '0x171c19'
    foreground: '0x87928a'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0x171c19'
    cursor: '0x87928a'

  # Normal colors
  normal:
    black:   '0x171c19'
    red:     '0xb16139'
    green:   '0x489963'
    yellow:  '0xa07e3b'
    blue:    '0x478c90'
    magenta: '0x55859b'
    cyan:    '0x1c9aa0'
    white:   '0x87928a'

  # Bright colors
  bright:
    black:   '0x5f6d64'
    red:     '0x9f713c'
    green:   '0x232a25'
    yellow:  '0x526057'
    blue:    '0x78877d'
    magenta: '0xdfe7e2'
    cyan:    '0x867469'
    white:   '0xecf4ee'

draw_bold_text_with_bright_colors: false
