# Base16 Outrun Dark 256 - alacritty color config
# Hugo Delahousse (http://github.com/hugodelahousse/)
colors:
  # Default colors
  primary:
    background: '0x00002a'
    foreground: '0xd0d0fa'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0x00002a'
    cursor: '0xd0d0fa'

  # Normal colors
  normal:
    black:   '0x00002a'
    red:     '0xff4242'
    green:   '0x59f176'
    yellow:  '0xf3e877'
    blue:    '0x66b0ff'
    magenta: '0xf10596'
    cyan:    '0x0ef0f0'
    white:   '0xd0d0fa'

  # Bright colors
  bright:
    black:   '0x50507a'
    red:     '0xff4242'
    green:   '0x59f176'
    yellow:  '0xf3e877'
    blue:    '0x66b0ff'
    magenta: '0xf10596'
    cyan:    '0x0ef0f0'
    white:   '0xf5f5ff'

  indexed_colors:
    - { index: 16, color: '0xfc8d28' }
    - { index: 17, color: '0xf003ef' }
    - { index: 18, color: '0x20204a' }
    - { index: 19, color: '0x30305a' }
    - { index: 20, color: '0xb0b0da' }
    - { index: 21, color: '0xe0e0ff' }
