# Base16 Material Lighter 256 - alacritty color config
# Nate Peterson
colors:
  # Default colors
  primary:
    background: '0xfafafa'
    foreground: '0x80cbc4'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0xfafafa'
    cursor: '0x80cbc4'

  # Normal colors
  normal:
    black:   '0xfafafa'
    red:     '0xff5370'
    green:   '0x91b859'
    yellow:  '0xffb62c'
    blue:    '0x6182b8'
    magenta: '0x7c4dff'
    cyan:    '0x39adb5'
    white:   '0x80cbc4'

  # Bright colors
  bright:
    black:   '0xccd7da'
    red:     '0xff5370'
    green:   '0x91b859'
    yellow:  '0xffb62c'
    blue:    '0x6182b8'
    magenta: '0x7c4dff'
    cyan:    '0x39adb5'
    white:   '0xffffff'

  indexed_colors:
    - { index: 16, color: '0xf76d47' }
    - { index: 17, color: '0xe53935' }
    - { index: 18, color: '0xe7eaec' }
    - { index: 19, color: '0xcceae7' }
    - { index: 20, color: '0x8796b0' }
    - { index: 21, color: '0x80cbc4' }
