# Base16 Ayu Mirage 256 - alacritty color config
# Khue Nguyen &lt;Z5483Y@gmail.com&gt;
colors:
  # Default colors
  primary:
    background: '0x171b24'
    foreground: '0xcccac2'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0x171b24'
    cursor: '0xcccac2'

  # Normal colors
  normal:
    black:   '0x171b24'
    red:     '0xf28779'
    green:   '0xd5ff80'
    yellow:  '0xffd173'
    blue:    '0x5ccfe6'
    magenta: '0xd4bfff'
    cyan:    '0x95e6cb'
    white:   '0xcccac2'

  # Bright colors
  bright:
    black:   '0x707a8c'
    red:     '0xf28779'
    green:   '0xd5ff80'
    yellow:  '0xffd173'
    blue:    '0x5ccfe6'
    magenta: '0xd4bfff'
    cyan:    '0x95e6cb'
    white:   '0xf3f4f5'

  indexed_colors:
    - { index: 16, color: '0xffad66' }
    - { index: 17, color: '0xf29e74' }
    - { index: 18, color: '0x1f2430' }
    - { index: 19, color: '0x242936' }
    - { index: 20, color: '0x8a9199' }
    - { index: 21, color: '0xd9d7ce' }
