# Base16 Windows 10 Light - alacritty color config
# Fergus Collins (https://github.com/C-Fergus)
colors:
  # Default colors
  primary:
    background: '0xf2f2f2'
    foreground: '0x767676'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0xf2f2f2'
    cursor: '0x767676'

  # Normal colors
  normal:
    black:   '0xf2f2f2'
    red:     '0xc50f1f'
    green:   '0x13a10e'
    yellow:  '0xc19c00'
    blue:    '0x0037da'
    magenta: '0x881798'
    cyan:    '0x3a96dd'
    white:   '0x767676'

  # Bright colors
  bright:
    black:   '0xcccccc'
    red:     '0xf9f1a5'
    green:   '0xe5e5e5'
    yellow:  '0xd9d9d9'
    blue:    '0xababab'
    magenta: '0x414141'
    cyan:    '0x16c60c'
    white:   '0x0c0c0c'

draw_bold_text_with_bright_colors: false
