# Base16 Helios - alacritty color config
# Alex Meyer (https://github.com/reyemxela)
colors:
  # Default colors
  primary:
    background: '0x1d2021'
    foreground: '0xd5d5d5'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0x1d2021'
    cursor: '0xd5d5d5'

  # Normal colors
  normal:
    black:   '0x1d2021'
    red:     '0xd72638'
    green:   '0x88b92d'
    yellow:  '0xf19d1a'
    blue:    '0x1e8bac'
    magenta: '0xbe4264'
    cyan:    '0x1ba595'
    white:   '0xd5d5d5'

  # Bright colors
  bright:
    black:   '0x6f7579'
    red:     '0xeb8413'
    green:   '0x383c3e'
    yellow:  '0x53585b'
    blue:    '0xcdcdcd'
    magenta: '0xdddddd'
    cyan:    '0xc85e0d'
    white:   '0xe5e5e5'

draw_bold_text_with_bright_colors: false
