# Base16 Atelier Dune Light - alacritty color config
# Bram de Haan (http://atelierbramdehaan.nl)
colors:
  # Default colors
  primary:
    background: '0xfefbec'
    foreground: '0x6e6b5e'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0xfefbec'
    cursor: '0x6e6b5e'

  # Normal colors
  normal:
    black:   '0xfefbec'
    red:     '0xd73737'
    green:   '0x60ac39'
    yellow:  '0xae9513'
    blue:    '0x6684e1'
    magenta: '0xb854d4'
    cyan:    '0x1fad83'
    white:   '0x6e6b5e'

  # Bright colors
  bright:
    black:   '0x999580'
    red:     '0xb65611'
    green:   '0xe8e4cf'
    yellow:  '0xa6a28c'
    blue:    '0x7d7a68'
    magenta: '0x292824'
    cyan:    '0xd43552'
    white:   '0x20201d'

draw_bold_text_with_bright_colors: false
