# Base16 Mellow Purple - alacritty color config
# gidsi
colors:
  # Default colors
  primary:
    background: '0x1e0528'
    foreground: '0xffeeff'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0x1e0528'
    cursor: '0xffeeff'

  # Normal colors
  normal:
    black:   '0x1e0528'
    red:     '0x00d9e9'
    green:   '0x05cb0d'
    yellow:  '0x955ae7'
    blue:    '0x550068'
    magenta: '0x8991bb'
    cyan:    '0xb900b1'
    white:   '0xffeeff'

  # Bright colors
  bright:
    black:   '0x320f55'
    red:     '0xaa00a3'
    green:   '0x1a092d'
    yellow:  '0x331354'
    blue:    '0x873582'
    magenta: '0xffeeff'
    cyan:    '0x4d6fff'
    white:   '0xf8c0ff'

draw_bold_text_with_bright_colors: false
