# Base16 UwUnicorn 256 - alacritty color config
# Fernando Marques (https://github.com/RakkiUwU) and Gabriel Fontes (https://github.com/Misterio77)
colors:
  # Default colors
  primary:
    background: '0x241b26'
    foreground: '0xeed5d9'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0x241b26'
    cursor: '0xeed5d9'

  # Normal colors
  normal:
    black:   '0x241b26'
    red:     '0x877bb6'
    green:   '0xc965bf'
    yellow:  '0xa84a73'
    blue:    '0x6a9eb5'
    magenta: '0x78a38f'
    cyan:    '0x9c5fce'
    white:   '0xeed5d9'

  # Bright colors
  bright:
    black:   '0x6c3cb2'
    red:     '0x877bb6'
    green:   '0xc965bf'
    yellow:  '0xa84a73'
    blue:    '0x6a9eb5'
    magenta: '0x78a38f'
    cyan:    '0x9c5fce'
    white:   '0xe4ccd0'

  indexed_colors:
    - { index: 16, color: '0xde5b44' }
    - { index: 17, color: '0xa3a079' }
    - { index: 18, color: '0x2f2a3f' }
    - { index: 19, color: '0x46354a' }
    - { index: 20, color: '0x7e5f83' }
    - { index: 21, color: '0xd9c2c6' }
