# Base16 Apprentice - alacritty color config
# romainl
colors:
  # Default colors
  primary:
    background: '0x262626'
    foreground: '0xbcbcbc'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0x262626'
    cursor: '0xbcbcbc'

  # Normal colors
  normal:
    black:   '0x262626'
    red:     '0x5f8787'
    green:   '0x87af87'
    yellow:  '0x5f8787'
    blue:    '0xffffaf'
    magenta: '0x87afd7'
    cyan:    '0x5f875f'
    white:   '0xbcbcbc'

  # Bright colors
  bright:
    black:   '0x6c6c6c'
    red:     '0xff8700'
    green:   '0x303030'
    yellow:  '0x333333'
    blue:    '0x787878'
    magenta: '0xc9c9c9'
    cyan:    '0x5f87af'
    white:   '0xffffff'

draw_bold_text_with_bright_colors: false
