# Base16 Windows 95 Light 256 - alacritty color config
# Fergus Collins (https://github.com/C-Fergus)
colors:
  # Default colors
  primary:
    background: '0xfcfcfc'
    foreground: '0x545454'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0xfcfcfc'
    cursor: '0x545454'

  # Normal colors
  normal:
    black:   '0xfcfcfc'
    red:     '0xa80000'
    green:   '0x00a800'
    yellow:  '0xa85400'
    blue:    '0x0000a8'
    magenta: '0xa800a8'
    cyan:    '0x00a8a8'
    white:   '0x545454'

  # Bright colors
  bright:
    black:   '0xa8a8a8'
    red:     '0xa80000'
    green:   '0x00a800'
    yellow:  '0xa85400'
    blue:    '0x0000a8'
    magenta: '0xa800a8'
    cyan:    '0x00a8a8'
    white:   '0x000000'

  indexed_colors:
    - { index: 16, color: '0xfcfc54' }
    - { index: 17, color: '0x54fc54' }
    - { index: 18, color: '0xe0e0e0' }
    - { index: 19, color: '0xc4c4c4' }
    - { index: 20, color: '0x7e7e7e' }
    - { index: 21, color: '0x2a2a2a' }
