# Base16 Horizon Dark 256 - alacritty color config
# Michaël Ball (http://github.com/michael-ball/)
colors:
  # Default colors
  primary:
    background: '0x1c1e26'
    foreground: '0xcbced0'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0x1c1e26'
    cursor: '0xcbced0'

  # Normal colors
  normal:
    black:   '0x1c1e26'
    red:     '0xe93c58'
    green:   '0xefaf8e'
    yellow:  '0xefb993'
    blue:    '0xdf5273'
    magenta: '0xb072d1'
    cyan:    '0x24a8b4'
    white:   '0xcbced0'

  # Bright colors
  bright:
    black:   '0x6f6f70'
    red:     '0xe93c58'
    green:   '0xefaf8e'
    yellow:  '0xefb993'
    blue:    '0xdf5273'
    magenta: '0xb072d1'
    cyan:    '0x24a8b4'
    white:   '0xe3e6ee'

  indexed_colors:
    - { index: 16, color: '0xe58d7d' }
    - { index: 17, color: '0xe4a382' }
    - { index: 18, color: '0x232530' }
    - { index: 19, color: '0x2e303e' }
    - { index: 20, color: '0x9da0a2' }
    - { index: 21, color: '0xdcdfe4' }
