# Base16 Atelier Seaside - alacritty color config
# Bram de Haan (http://atelierbramdehaan.nl)
colors:
  # Default colors
  primary:
    background: '0x131513'
    foreground: '0x8ca68c'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0x131513'
    cursor: '0x8ca68c'

  # Normal colors
  normal:
    black:   '0x131513'
    red:     '0xe6193c'
    green:   '0x29a329'
    yellow:  '0x98981b'
    blue:    '0x3d62f5'
    magenta: '0xad2bee'
    cyan:    '0x1999b3'
    white:   '0x8ca68c'

  # Bright colors
  bright:
    black:   '0x687d68'
    red:     '0x87711d'
    green:   '0x242924'
    yellow:  '0x5e6e5e'
    blue:    '0x809980'
    magenta: '0xcfe8cf'
    cyan:    '0xe619c3'
    white:   '0xf4fbf4'

draw_bold_text_with_bright_colors: false
