# Base16 Brush Trees - alacritty color config
# Abraham White &lt;abelincoln.white@gmail.com&gt;
colors:
  # Default colors
  primary:
    background: '0xe3efef'
    foreground: '0x6d828e'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0xe3efef'
    cursor: '0x6d828e'

  # Normal colors
  normal:
    black:   '0xe3efef'
    red:     '0xb38686'
    green:   '0x87b386'
    yellow:  '0xaab386'
    blue:    '0x868cb3'
    magenta: '0xb386b2'
    cyan:    '0x86b3b3'
    white:   '0x6d828e'

  # Bright colors
  bright:
    black:   '0x98afb5'
    red:     '0xd8bba2'
    green:   '0xc9dbdc'
    yellow:  '0xb0c5c8'
    blue:    '0x8299a1'
    magenta: '0x5a6d7a'
    cyan:    '0xb39f9f'
    white:   '0x485867'

draw_bold_text_with_bright_colors: false
