# Base16 Atelier Estuary Light 256 - alacritty color config
# Bram de Haan (http://atelierbramdehaan.nl)
colors:
  # Default colors
  primary:
    background: '0xf4f3ec'
    foreground: '0x5f5e4e'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0xf4f3ec'
    cursor: '0x5f5e4e'

  # Normal colors
  normal:
    black:   '0xf4f3ec'
    red:     '0xba6236'
    green:   '0x7d9726'
    yellow:  '0xa5980d'
    blue:    '0x36a166'
    magenta: '0x5f9182'
    cyan:    '0x5b9d48'
    white:   '0x5f5e4e'

  # Bright colors
  bright:
    black:   '0x878573'
    red:     '0xba6236'
    green:   '0x7d9726'
    yellow:  '0xa5980d'
    blue:    '0x36a166'
    magenta: '0x5f9182'
    cyan:    '0x5b9d48'
    white:   '0x22221b'

  indexed_colors:
    - { index: 16, color: '0xae7313' }
    - { index: 17, color: '0x9d6c7c' }
    - { index: 18, color: '0xe7e6df' }
    - { index: 19, color: '0x929181' }
    - { index: 20, color: '0x6c6b5a' }
    - { index: 21, color: '0x302f27' }
