# Base16 Material Vivid - alacritty color config
# joshyrobot
colors:
  # Default colors
  primary:
    background: '0x202124'
    foreground: '0x80868b'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0x202124'
    cursor: '0x80868b'

  # Normal colors
  normal:
    black:   '0x202124'
    red:     '0xf44336'
    green:   '0x00e676'
    yellow:  '0xffeb3b'
    blue:    '0x2196f3'
    magenta: '0x673ab7'
    cyan:    '0x00bcd4'
    white:   '0x80868b'

  # Bright colors
  bright:
    black:   '0x44464d'
    red:     '0xff9800'
    green:   '0x27292c'
    yellow:  '0x323639'
    blue:    '0x676c71'
    magenta: '0x9e9e9e'
    cyan:    '0x8d6e63'
    white:   '0xffffff'

draw_bold_text_with_bright_colors: false
