# Base16 Solar Flare Light 256 - alacritty color config
# Chuck Harmston (https://chuck.harmston.ch)
colors:
  # Default colors
  primary:
    background: '0xf5f7fa'
    foreground: '0x586875'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0xf5f7fa'
    cursor: '0x586875'

  # Normal colors
  normal:
    black:   '0xf5f7fa'
    red:     '0xef5253'
    green:   '0x7cc844'
    yellow:  '0xe4b51c'
    blue:    '0x33b5e1'
    magenta: '0xa363d5'
    cyan:    '0x52cbb0'
    white:   '0x586875'

  # Bright colors
  bright:
    black:   '0x85939e'
    red:     '0xef5253'
    green:   '0x7cc844'
    yellow:  '0xe4b51c'
    blue:    '0x33b5e1'
    magenta: '0xa363d5'
    cyan:    '0x52cbb0'
    white:   '0x18262f'

  indexed_colors:
    - { index: 16, color: '0xe66b2b' }
    - { index: 17, color: '0xd73c9a' }
    - { index: 18, color: '0xe8e9ed' }
    - { index: 19, color: '0xa6afb8' }
    - { index: 20, color: '0x667581' }
    - { index: 21, color: '0x222e38' }
