# Base16 Still Alive 256 - alacritty color config
# Derrick McKee (derrick.mckee@gmail.com)
colors:
  # Default colors
  primary:
    background: '0xf0f0f0'
    foreground: '0xd80000'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0xf0f0f0'
    cursor: '0xd80000'

  # Normal colors
  normal:
    black:   '0xf0f0f0'
    red:     '0x487830'
    green:   '0x5c5c6a'
    yellow:  '0x426395'
    blue:    '0x001878'
    magenta: '0x900000'
    cyan:    '0x2c3c57'
    white:   '0xd80000'

  # Bright colors
  bright:
    black:   '0xf01818'
    red:     '0x487830'
    green:   '0x5c5c6a'
    yellow:  '0x426395'
    blue:    '0x001878'
    magenta: '0x900000'
    cyan:    '0x2c3c57'
    white:   '0x30a860'

  indexed_colors:
    - { index: 16, color: '0x183048' }
    - { index: 17, color: '0x140c0d' }
    - { index: 18, color: '0xf0d848' }
    - { index: 19, color: '0xfff018' }
    - { index: 20, color: '0xf00000' }
    - { index: 21, color: '0x489000' }
