# Base16 One Light - alacritty color config
# Daniel Pfeifer (http://github.com/purpleKarrot)
colors:
  # Default colors
  primary:
    background: '0xfafafa'
    foreground: '0x383a42'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0xfafafa'
    cursor: '0x383a42'

  # Normal colors
  normal:
    black:   '0xfafafa'
    red:     '0xca1243'
    green:   '0x50a14f'
    yellow:  '0xc18401'
    blue:    '0x4078f2'
    magenta: '0xa626a4'
    cyan:    '0x0184bc'
    white:   '0x383a42'

  # Bright colors
  bright:
    black:   '0xa0a1a7'
    red:     '0xd75f00'
    green:   '0xf0f0f1'
    yellow:  '0xe5e5e6'
    blue:    '0x696c77'
    magenta: '0x202227'
    cyan:    '0x986801'
    white:   '0x090a0b'

draw_bold_text_with_bright_colors: false
