# Base16 Windows High Contrast Light - alacritty color config
# Fergus Collins (https://github.com/C-Fergus)
colors:
  # Default colors
  primary:
    background: '0xfcfcfc'
    foreground: '0x545454'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0xfcfcfc'
    cursor: '0x545454'

  # Normal colors
  normal:
    black:   '0xfcfcfc'
    red:     '0x800000'
    green:   '0x008000'
    yellow:  '0x808000'
    blue:    '0x000080'
    magenta: '0x800080'
    cyan:    '0x008080'
    white:   '0x545454'

  # Bright colors
  bright:
    black:   '0xc0c0c0'
    red:     '0xfcfc54'
    green:   '0xe8e8e8'
    yellow:  '0xd4d4d4'
    blue:    '0x7e7e7e'
    magenta: '0x2a2a2a'
    cyan:    '0x54fc54'
    white:   '0x000000'

draw_bold_text_with_bright_colors: false
