# Base16 Atlas 256 - alacritty color config
# Alex Lende (https://ajlende.com)
colors:
  # Default colors
  primary:
    background: '0x002635'
    foreground: '0xa1a19a'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0x002635'
    cursor: '0xa1a19a'

  # Normal colors
  normal:
    black:   '0x002635'
    red:     '0xff5a67'
    green:   '0x7fc06e'
    yellow:  '0xffcc1b'
    blue:    '0x5dd7b9'
    magenta: '0x9a70a4'
    cyan:    '0x14747e'
    white:   '0xa1a19a'

  # Bright colors
  bright:
    black:   '0x6c8b91'
    red:     '0xff5a67'
    green:   '0x7fc06e'
    yellow:  '0xffcc1b'
    blue:    '0x5dd7b9'
    magenta: '0x9a70a4'
    cyan:    '0x14747e'
    white:   '0xfafaf8'

  indexed_colors:
    - { index: 16, color: '0xf08e48' }
    - { index: 17, color: '0xc43060' }
    - { index: 18, color: '0x00384d' }
    - { index: 19, color: '0x517f8d' }
    - { index: 20, color: '0x869696' }
    - { index: 21, color: '0xe6e6dc' }
