# Base16 Tokyo City Terminal Dark 256 - alacritty color config
# Michaël Ball
colors:
  # Default colors
  primary:
    background: '0x171d23'
    foreground: '0xd8e2ec'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0x171d23'
    cursor: '0xd8e2ec'

  # Normal colors
  normal:
    black:   '0x171d23'
    red:     '0xd95468'
    green:   '0x8bd49c'
    yellow:  '0xebbf83'
    blue:    '0x539afc'
    magenta: '0xb62d65'
    cyan:    '0x70e1e8'
    white:   '0xd8e2ec'

  # Bright colors
  bright:
    black:   '0x526270'
    red:     '0xd95468'
    green:   '0x8bd49c'
    yellow:  '0xebbf83'
    blue:    '0x539afc'
    magenta: '0xb62d65'
    cyan:    '0x70e1e8'
    white:   '0xfbfbfd'

  indexed_colors:
    - { index: 16, color: '0xff9e64' }
    - { index: 17, color: '0xdd9d82' }
    - { index: 18, color: '0x1d252c' }
    - { index: 19, color: '0x28323a' }
    - { index: 20, color: '0xb7c5d3' }
    - { index: 21, color: '0xf6f6f8' }
