# Base16 darkmoss - alacritty color config
# Gabriel Avanzi (https://github.com/avanzzzi)
colors:
  # Default colors
  primary:
    background: '0x171e1f'
    foreground: '0xc7c7a5'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0x171e1f'
    cursor: '0xc7c7a5'

  # Normal colors
  normal:
    black:   '0x171e1f'
    red:     '0xff4658'
    green:   '0x499180'
    yellow:  '0xfdb11f'
    blue:    '0x498091'
    magenta: '0x9bc0c8'
    cyan:    '0x66d9ef'
    white:   '0xc7c7a5'

  # Bright colors
  bright:
    black:   '0x555e5f'
    red:     '0xe6db74'
    green:   '0x252c2d'
    yellow:  '0x373c3d'
    blue:    '0x818f80'
    magenta: '0xe3e3c8'
    cyan:    '0xd27b53'
    white:   '0xe1eaef'

draw_bold_text_with_bright_colors: false
