# Base16 iA Light 256 - alacritty color config
# iA Inc. (modified by aramisgithub)
colors:
  # Default colors
  primary:
    background: '0xf6f6f6'
    foreground: '0x181818'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0xf6f6f6'
    cursor: '0x181818'

  # Normal colors
  normal:
    black:   '0xf6f6f6'
    red:     '0x9c5a02'
    green:   '0x38781c'
    yellow:  '0xc48218'
    blue:    '0x48bac2'
    magenta: '0xa94598'
    cyan:    '0x2d6bb1'
    white:   '0x181818'

  # Bright colors
  bright:
    black:   '0x898989'
    red:     '0x9c5a02'
    green:   '0x38781c'
    yellow:  '0xc48218'
    blue:    '0x48bac2'
    magenta: '0xa94598'
    cyan:    '0x2d6bb1'
    white:   '0xf8f8f8'

  indexed_colors:
    - { index: 16, color: '0xc43e18' }
    - { index: 17, color: '0x8b6c37' }
    - { index: 18, color: '0xdedede' }
    - { index: 19, color: '0xbde5f2' }
    - { index: 20, color: '0x767676' }
    - { index: 21, color: '0xe8e8e8' }
