# Base16 Rebecca - alacritty color config
# Victor Borja (http://github.com/vic) based on Rebecca Theme (http://github.com/vic/rebecca-theme)
colors:
  # Default colors
  primary:
    background: '0x292a44'
    foreground: '0xf1eff8'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0x292a44'
    cursor: '0xf1eff8'

  # Normal colors
  normal:
    black:   '0x292a44'
    red:     '0xa0a0c5'
    green:   '0x6dfedf'
    yellow:  '0xae81ff'
    blue:    '0x2de0a7'
    magenta: '0x7aa5ff'
    cyan:    '0x8eaee0'
    white:   '0xf1eff8'

  # Bright colors
  bright:
    black:   '0x666699'
    red:     '0xefe4a1'
    green:   '0x663399'
    yellow:  '0x383a62'
    blue:    '0xa0a0c5'
    magenta: '0xccccff'
    cyan:    '0xff79c6'
    white:   '0x53495d'

draw_bold_text_with_bright_colors: false
