# Base16 Catppuccin 256 - alacritty color config
# Pocco81 (https://github.com/pocco81)
colors:
  # Default colors
  primary:
    background: '0x1e1e28'
    foreground: '0xd7dae0'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0x1e1e28'
    cursor: '0xd7dae0'

  # Normal colors
  normal:
    black:   '0x1e1e28'
    red:     '0xf28fad'
    green:   '0xabe9b3'
    yellow:  '0xfae3b0'
    blue:    '0x96cdfb'
    magenta: '0xddb6f2'
    cyan:    '0xb5e8e0'
    white:   '0xd7dae0'

  # Bright colors
  bright:
    black:   '0x575268'
    red:     '0xf28fad'
    green:   '0xabe9b3'
    yellow:  '0xfae3b0'
    blue:    '0x96cdfb'
    magenta: '0xddb6f2'
    cyan:    '0xb5e8e0'
    white:   '0xc9cbff'

  indexed_colors:
    - { index: 16, color: '0xf8bd96' }
    - { index: 17, color: '0xf2cdcd' }
    - { index: 18, color: '0x1a1826' }
    - { index: 19, color: '0x302d41' }
    - { index: 20, color: '0x6e6c7c' }
    - { index: 21, color: '0xf5e0dc' }
