# Base16 Seti UI 256 - alacritty color config
# 
colors:
  # Default colors
  primary:
    background: '0x151718'
    foreground: '0xd6d6d6'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0x151718'
    cursor: '0xd6d6d6'

  # Normal colors
  normal:
    black:   '0x151718'
    red:     '0xcd3f45'
    green:   '0x9fca56'
    yellow:  '0xe6cd69'
    blue:    '0x55b5db'
    magenta: '0xa074c4'
    cyan:    '0x55dbbe'
    white:   '0xd6d6d6'

  # Bright colors
  bright:
    black:   '0x41535b'
    red:     '0xcd3f45'
    green:   '0x9fca56'
    yellow:  '0xe6cd69'
    blue:    '0x55b5db'
    magenta: '0xa074c4'
    cyan:    '0x55dbbe'
    white:   '0xffffff'

  indexed_colors:
    - { index: 16, color: '0xdb7b55' }
    - { index: 17, color: '0x8a553f' }
    - { index: 18, color: '0x282a2b' }
    - { index: 19, color: '0x3b758c' }
    - { index: 20, color: '0x43a5d5' }
    - { index: 21, color: '0xeeeeee' }
