# Base16 Windows High Contrast Light 256 - alacritty color config
# Fergus Collins (https://github.com/C-Fergus)
colors:
  # Default colors
  primary:
    background: '0xfcfcfc'
    foreground: '0x545454'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0xfcfcfc'
    cursor: '0x545454'

  # Normal colors
  normal:
    black:   '0xfcfcfc'
    red:     '0x800000'
    green:   '0x008000'
    yellow:  '0x808000'
    blue:    '0x000080'
    magenta: '0x800080'
    cyan:    '0x008080'
    white:   '0x545454'

  # Bright colors
  bright:
    black:   '0xc0c0c0'
    red:     '0x800000'
    green:   '0x008000'
    yellow:  '0x808000'
    blue:    '0x000080'
    magenta: '0x800080'
    cyan:    '0x008080'
    white:   '0x000000'

  indexed_colors:
    - { index: 16, color: '0xfcfc54' }
    - { index: 17, color: '0x54fc54' }
    - { index: 18, color: '0xe8e8e8' }
    - { index: 19, color: '0xd4d4d4' }
    - { index: 20, color: '0x7e7e7e' }
    - { index: 21, color: '0x2a2a2a' }
