# Base16 XCode Dusk 256 - alacritty color config
# Elsa Gonsiorowski (https://github.com/gonsie)
colors:
  # Default colors
  primary:
    background: '0x282b35'
    foreground: '0x939599'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0x282b35'
    cursor: '0x939599'

  # Normal colors
  normal:
    black:   '0x282b35'
    red:     '0xb21889'
    green:   '0xdf0002'
    yellow:  '0x438288'
    blue:    '0x790ead'
    magenta: '0xb21889'
    cyan:    '0x00a0be'
    white:   '0x939599'

  # Bright colors
  bright:
    black:   '0x686a71'
    red:     '0xb21889'
    green:   '0xdf0002'
    yellow:  '0x438288'
    blue:    '0x790ead'
    magenta: '0xb21889'
    cyan:    '0x00a0be'
    white:   '0xbebfc2'

  indexed_colors:
    - { index: 16, color: '0x786dc5' }
    - { index: 17, color: '0xc77c48' }
    - { index: 18, color: '0x3d4048' }
    - { index: 19, color: '0x53555d' }
    - { index: 20, color: '0x7e8086' }
    - { index: 21, color: '0xa9aaae' }
