# Base16 Tomorrow Night Eighties 256 - alacritty color config
# Chris Kempson (http://chriskempson.com)
colors:
  # Default colors
  primary:
    background: '0x2d2d2d'
    foreground: '0xcccccc'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0x2d2d2d'
    cursor: '0xcccccc'

  # Normal colors
  normal:
    black:   '0x2d2d2d'
    red:     '0xf2777a'
    green:   '0x99cc99'
    yellow:  '0xffcc66'
    blue:    '0x6699cc'
    magenta: '0xcc99cc'
    cyan:    '0x66cccc'
    white:   '0xcccccc'

  # Bright colors
  bright:
    black:   '0x999999'
    red:     '0xf2777a'
    green:   '0x99cc99'
    yellow:  '0xffcc66'
    blue:    '0x6699cc'
    magenta: '0xcc99cc'
    cyan:    '0x66cccc'
    white:   '0xffffff'

  indexed_colors:
    - { index: 16, color: '0xf99157' }
    - { index: 17, color: '0xa3685a' }
    - { index: 18, color: '0x393939' }
    - { index: 19, color: '0x515151' }
    - { index: 20, color: '0xb4b7b4' }
    - { index: 21, color: '0xe0e0e0' }
