# Base16 Blue Forest 256 - alacritty color config
# alonsodomin (https://github.com/alonsodomin)
colors:
  # Default colors
  primary:
    background: '0x141f2e'
    foreground: '0xffcc33'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0x141f2e'
    cursor: '0xffcc33'

  # Normal colors
  normal:
    black:   '0x141f2e'
    red:     '0xfffab1'
    green:   '0x80ff80'
    yellow:  '0x91ccff'
    blue:    '0xa2cff5'
    magenta: '0x0099ff'
    cyan:    '0x80ff80'
    white:   '0xffcc33'

  # Bright colors
  bright:
    black:   '0xa0ffa0'
    red:     '0xfffab1'
    green:   '0x80ff80'
    yellow:  '0x91ccff'
    blue:    '0xa2cff5'
    magenta: '0x0099ff'
    cyan:    '0x80ff80'
    white:   '0x375780'

  indexed_colors:
    - { index: 16, color: '0xff8080' }
    - { index: 17, color: '0xe7e7e7' }
    - { index: 18, color: '0x1e5c1e' }
    - { index: 19, color: '0x273e5c' }
    - { index: 20, color: '0x1e5c1e' }
    - { index: 21, color: '0x91ccff' }
