# Base16 Cupcake 256 - alacritty color config
# Chris Kempson (http://chriskempson.com)
colors:
  # Default colors
  primary:
    background: '0xfbf1f2'
    foreground: '0x8b8198'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0xfbf1f2'
    cursor: '0x8b8198'

  # Normal colors
  normal:
    black:   '0xfbf1f2'
    red:     '0xd57e85'
    green:   '0xa3b367'
    yellow:  '0xdcb16c'
    blue:    '0x7297b9'
    magenta: '0xbb99b4'
    cyan:    '0x69a9a7'
    white:   '0x8b8198'

  # Bright colors
  bright:
    black:   '0xbfb9c6'
    red:     '0xd57e85'
    green:   '0xa3b367'
    yellow:  '0xdcb16c'
    blue:    '0x7297b9'
    magenta: '0xbb99b4'
    cyan:    '0x69a9a7'
    white:   '0x585062'

  indexed_colors:
    - { index: 16, color: '0xebb790' }
    - { index: 17, color: '0xbaa58c' }
    - { index: 18, color: '0xf2f1f4' }
    - { index: 19, color: '0xd8d5dd' }
    - { index: 20, color: '0xa59daf' }
    - { index: 21, color: '0x72677e' }
