# Base16 Qualia - alacritty color config
# isaacwhanson
colors:
  # Default colors
  primary:
    background: '0x101010'
    foreground: '0xc0c0c0'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0x101010'
    cursor: '0xc0c0c0'

  # Normal colors
  normal:
    black:   '0x101010'
    red:     '0xefa6a2'
    green:   '0x80c990'
    yellow:  '0xe6a3dc'
    blue:    '0x50cacd'
    magenta: '0xe0af85'
    cyan:    '0xc8c874'
    white:   '0xc0c0c0'

  # Bright colors
  bright:
    black:   '0x454545'
    red:     '0xa3b8ef'
    green:   '0x454545'
    yellow:  '0x454545'
    blue:    '0x808080'
    magenta: '0xc0c0c0'
    cyan:    '0x808080'
    white:   '0x454545'

draw_bold_text_with_bright_colors: false
