# Base16 summercamp - alacritty color config
# zoe firi (zoefiri.github.io)
colors:
  # Default colors
  primary:
    background: '0x1c1810'
    foreground: '0x736e55'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0x1c1810'
    cursor: '0x736e55'

  # Normal colors
  normal:
    black:   '0x1c1810'
    red:     '0xe35142'
    green:   '0x5ceb5a'
    yellow:  '0xf2ff27'
    blue:    '0x489bf0'
    magenta: '0xff8080'
    cyan:    '0x5aebbc'
    white:   '0x736e55'

  # Bright colors
  bright:
    black:   '0x504b38'
    red:     '0xfba11b'
    green:   '0x2a261c'
    yellow:  '0x3a3527'
    blue:    '0x5f5b45'
    magenta: '0xbab696'
    cyan:    '0xf69be7'
    white:   '0xf8f5de'

draw_bold_text_with_bright_colors: false
