# Base16 Classic Light 256 - alacritty color config
# Jason Heeris (http://heeris.id.au)
colors:
  # Default colors
  primary:
    background: '0xf5f5f5'
    foreground: '0x303030'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0xf5f5f5'
    cursor: '0x303030'

  # Normal colors
  normal:
    black:   '0xf5f5f5'
    red:     '0xac4142'
    green:   '0x90a959'
    yellow:  '0xf4bf75'
    blue:    '0x6a9fb5'
    magenta: '0xaa759f'
    cyan:    '0x75b5aa'
    white:   '0x303030'

  # Bright colors
  bright:
    black:   '0xb0b0b0'
    red:     '0xac4142'
    green:   '0x90a959'
    yellow:  '0xf4bf75'
    blue:    '0x6a9fb5'
    magenta: '0xaa759f'
    cyan:    '0x75b5aa'
    white:   '0x151515'

  indexed_colors:
    - { index: 16, color: '0xd28445' }
    - { index: 17, color: '0x8f5536' }
    - { index: 18, color: '0xe0e0e0' }
    - { index: 19, color: '0xd0d0d0' }
    - { index: 20, color: '0x505050' }
    - { index: 21, color: '0x202020' }
