# Base16 Da One White - alacritty color config
# NNB (https://github.com/NNBnh)
colors:
  # Default colors
  primary:
    background: '0xffffff'
    foreground: '0x181818'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0xffffff'
    cursor: '0x181818'

  # Normal colors
  normal:
    black:   '0xffffff'
    red:     '0xde5d6e'
    green:   '0x76a85d'
    yellow:  '0xb3684f'
    blue:    '0x5890f8'
    magenta: '0xc173d1'
    cyan:    '0x64b5a7'
    white:   '0x181818'

  # Bright colors
  bright:
    black:   '0x585858'
    red:     '0xff9470'
    green:   '0xc8c8c8'
    yellow:  '0x888888'
    blue:    '0x282828'
    magenta: '0x000000'
    cyan:    '0xb3684f'
    white:   '0x000000'

draw_bold_text_with_bright_colors: false
