# Base16 Nebula - alacritty color config
# Gabriel Fontes (https://github.com/Misterio77)
colors:
  # Default colors
  primary:
    background: '0x22273b'
    foreground: '0xa4a6a9'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0x22273b'
    cursor: '0xa4a6a9'

  # Normal colors
  normal:
    black:   '0x22273b'
    red:     '0x777abc'
    green:   '0x6562a8'
    yellow:  '0x4f9062'
    blue:    '0x4d6bb6'
    magenta: '0x716cae'
    cyan:    '0x226f68'
    white:   '0xa4a6a9'

  # Bright colors
  bright:
    black:   '0x6e6f72'
    red:     '0x94929e'
    green:   '0x414f60'
    yellow:  '0x5a8380'
    blue:    '0x87888b'
    magenta: '0xc7c9cd'
    cyan:    '0x8c70a7'
    white:   '0x8dbdaa'

draw_bold_text_with_bright_colors: false
