# Base16 Primer Dark 256 - alacritty color config
# Jimmy Lin
colors:
  # Default colors
  primary:
    background: '0x010409'
    foreground: '0xb1bac4'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0x010409'
    cursor: '0xb1bac4'

  # Normal colors
  normal:
    black:   '0x010409'
    red:     '0xff7b72'
    green:   '0x3fb950'
    yellow:  '0xd29922'
    blue:    '0x58a6ff'
    magenta: '0xf778ba'
    cyan:    '0xa5d6ff'
    white:   '0xb1bac4'

  # Bright colors
  bright:
    black:   '0x484f58'
    red:     '0xff7b72'
    green:   '0x3fb950'
    yellow:  '0xd29922'
    blue:    '0x58a6ff'
    magenta: '0xf778ba'
    cyan:    '0xa5d6ff'
    white:   '0xf0f6fc'

  indexed_colors:
    - { index: 16, color: '0xf0883e' }
    - { index: 17, color: '0xbd561d' }
    - { index: 18, color: '0x21262d' }
    - { index: 19, color: '0x30363d' }
    - { index: 20, color: '0x8b949e' }
    - { index: 21, color: '0xc9d1d9' }
