# Base16 Heetch Light 256 - alacritty color config
# Geoffrey Teale (tealeg@gmail.com)
colors:
  # Default colors
  primary:
    background: '0xfeffff'
    foreground: '0x5a496e'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0xfeffff'
    cursor: '0x5a496e'

  # Normal colors
  normal:
    black:   '0xfeffff'
    red:     '0x27d9d5'
    green:   '0xf80059'
    yellow:  '0x5ba2b6'
    blue:    '0x47f9f5'
    magenta: '0xbd0152'
    cyan:    '0xc33678'
    white:   '0x5a496e'

  # Bright colors
  bright:
    black:   '0x9c92a8'
    red:     '0x27d9d5'
    green:   '0xf80059'
    yellow:  '0x5ba2b6'
    blue:    '0x47f9f5'
    magenta: '0xbd0152'
    cyan:    '0xc33678'
    white:   '0x190134'

  indexed_colors:
    - { index: 16, color: '0xbdb6c5' }
    - { index: 17, color: '0xdedae2' }
    - { index: 18, color: '0x392551' }
    - { index: 19, color: '0x7b6d8b' }
    - { index: 20, color: '0xddd6e5' }
    - { index: 21, color: '0x470546' }
