# Base16 Gruvbox Material Dark, Soft 256 - alacritty color config
# Mayush Kumar (https://github.com/MayushKumar), sainnhe (https://github.com/sainnhe/gruvbox-material-vscode)
colors:
  # Default colors
  primary:
    background: '0x32302f'
    foreground: '0xddc7a1'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0x32302f'
    cursor: '0xddc7a1'

  # Normal colors
  normal:
    black:   '0x32302f'
    red:     '0xea6962'
    green:   '0xa9b665'
    yellow:  '0xd8a657'
    blue:    '0x7daea3'
    magenta: '0xd3869b'
    cyan:    '0x89b482'
    white:   '0xddc7a1'

  # Bright colors
  bright:
    black:   '0x7c6f64'
    red:     '0xea6962'
    green:   '0xa9b665'
    yellow:  '0xd8a657'
    blue:    '0x7daea3'
    magenta: '0xd3869b'
    cyan:    '0x89b482'
    white:   '0xfbf1c7'

  indexed_colors:
    - { index: 16, color: '0xe78a4e' }
    - { index: 17, color: '0xbd6f3e' }
    - { index: 18, color: '0x3c3836' }
    - { index: 19, color: '0x5a524c' }
    - { index: 20, color: '0xbdae93' }
    - { index: 21, color: '0xebdbb2' }
