# Base16 3024 256 - alacritty color config
# Jan T. Sott (http://github.com/idleberg)
colors:
  # Default colors
  primary:
    background: '0x090300'
    foreground: '0xa5a2a2'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0x090300'
    cursor: '0xa5a2a2'

  # Normal colors
  normal:
    black:   '0x090300'
    red:     '0xdb2d20'
    green:   '0x01a252'
    yellow:  '0xfded02'
    blue:    '0x01a0e4'
    magenta: '0xa16a94'
    cyan:    '0xb5e4f4'
    white:   '0xa5a2a2'

  # Bright colors
  bright:
    black:   '0x5c5855'
    red:     '0xdb2d20'
    green:   '0x01a252'
    yellow:  '0xfded02'
    blue:    '0x01a0e4'
    magenta: '0xa16a94'
    cyan:    '0xb5e4f4'
    white:   '0xf7f7f7'

  indexed_colors:
    - { index: 16, color: '0xe8bbd0' }
    - { index: 17, color: '0xcdab53' }
    - { index: 18, color: '0x3a3432' }
    - { index: 19, color: '0x4a4543' }
    - { index: 20, color: '0x807d7c' }
    - { index: 21, color: '0xd6d5d4' }
