# Base16 Chalk 256 - alacritty color config
# Chris Kempson (http://chriskempson.com)
colors:
  # Default colors
  primary:
    background: '0x151515'
    foreground: '0xd0d0d0'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0x151515'
    cursor: '0xd0d0d0'

  # Normal colors
  normal:
    black:   '0x151515'
    red:     '0xfb9fb1'
    green:   '0xacc267'
    yellow:  '0xddb26f'
    blue:    '0x6fc2ef'
    magenta: '0xe1a3ee'
    cyan:    '0x12cfc0'
    white:   '0xd0d0d0'

  # Bright colors
  bright:
    black:   '0x505050'
    red:     '0xfb9fb1'
    green:   '0xacc267'
    yellow:  '0xddb26f'
    blue:    '0x6fc2ef'
    magenta: '0xe1a3ee'
    cyan:    '0x12cfc0'
    white:   '0xf5f5f5'

  indexed_colors:
    - { index: 16, color: '0xeda987' }
    - { index: 17, color: '0xdeaf8f' }
    - { index: 18, color: '0x202020' }
    - { index: 19, color: '0x303030' }
    - { index: 20, color: '0xb0b0b0' }
    - { index: 21, color: '0xe0e0e0' }
