# Base16 Atelier Cave Light - alacritty color config
# Bram de Haan (http://atelierbramdehaan.nl)
colors:
  # Default colors
  primary:
    background: '0xefecf4'
    foreground: '0x585260'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0xefecf4'
    cursor: '0x585260'

  # Normal colors
  normal:
    black:   '0xefecf4'
    red:     '0xbe4678'
    green:   '0x2a9292'
    yellow:  '0xa06e3b'
    blue:    '0x576ddb'
    magenta: '0x955ae7'
    cyan:    '0x398bc6'
    white:   '0x585260'

  # Bright colors
  bright:
    black:   '0x7e7887'
    red:     '0xaa573c'
    green:   '0xe2dfe7'
    yellow:  '0x8b8792'
    blue:    '0x655f6d'
    magenta: '0x26232a'
    cyan:    '0xbf40bf'
    white:   '0x19171c'

draw_bold_text_with_bright_colors: false
