# Base16 Mexico Light - alacritty color config
# Sheldon Johnson
colors:
  # Default colors
  primary:
    background: '0xf8f8f8'
    foreground: '0x383838'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0xf8f8f8'
    cursor: '0x383838'

  # Normal colors
  normal:
    black:   '0xf8f8f8'
    red:     '0xab4642'
    green:   '0x538947'
    yellow:  '0xf79a0e'
    blue:    '0x7cafc2'
    magenta: '0x96609e'
    cyan:    '0x4b8093'
    white:   '0x383838'

  # Bright colors
  bright:
    black:   '0xb8b8b8'
    red:     '0xdc9656'
    green:   '0xe8e8e8'
    yellow:  '0xd8d8d8'
    blue:    '0x585858'
    magenta: '0x282828'
    cyan:    '0xa16946'
    white:   '0x181818'

draw_bold_text_with_bright_colors: false
