# Base16 London Tube - alacritty color config
# Jan T. Sott
colors:
  # Default colors
  primary:
    background: '0x231f20'
    foreground: '0xd9d8d8'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0x231f20'
    cursor: '0xd9d8d8'

  # Normal colors
  normal:
    black:   '0x231f20'
    red:     '0xee2e24'
    green:   '0x00853e'
    yellow:  '0xffd204'
    blue:    '0x009ddc'
    magenta: '0x98005d'
    cyan:    '0x85cebc'
    white:   '0xd9d8d8'

  # Bright colors
  bright:
    black:   '0x737171'
    red:     '0xf386a1'
    green:   '0x1c3f95'
    yellow:  '0x5a5758'
    blue:    '0x959ca1'
    magenta: '0xe7e7e8'
    cyan:    '0xb06110'
    white:   '0xffffff'

draw_bold_text_with_bright_colors: false
