# Base16 Ocean - alacritty color config
# Chris Kempson (http://chriskempson.com)
colors:
  # Default colors
  primary:
    background: '0x2b303b'
    foreground: '0xc0c5ce'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0x2b303b'
    cursor: '0xc0c5ce'

  # Normal colors
  normal:
    black:   '0x2b303b'
    red:     '0xbf616a'
    green:   '0xa3be8c'
    yellow:  '0xebcb8b'
    blue:    '0x8fa1b3'
    magenta: '0xb48ead'
    cyan:    '0x96b5b4'
    white:   '0xc0c5ce'

  # Bright colors
  bright:
    black:   '0x65737e'
    red:     '0xd08770'
    green:   '0x343d46'
    yellow:  '0x4f5b66'
    blue:    '0xa7adba'
    magenta: '0xdfe1e8'
    cyan:    '0xab7967'
    white:   '0xeff1f5'

draw_bold_text_with_bright_colors: false
