# Base16 Codeschool 256 - alacritty color config
# blockloop
colors:
  # Default colors
  primary:
    background: '0x232c31'
    foreground: '0x9ea7a6'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0x232c31'
    cursor: '0x9ea7a6'

  # Normal colors
  normal:
    black:   '0x232c31'
    red:     '0x2a5491'
    green:   '0x237986'
    yellow:  '0xa03b1e'
    blue:    '0x484d79'
    magenta: '0xc59820'
    cyan:    '0xb02f30'
    white:   '0x9ea7a6'

  # Bright colors
  bright:
    black:   '0x3f4944'
    red:     '0x2a5491'
    green:   '0x237986'
    yellow:  '0xa03b1e'
    blue:    '0x484d79'
    magenta: '0xc59820'
    cyan:    '0xb02f30'
    white:   '0xb5d8f6'

  indexed_colors:
    - { index: 16, color: '0x43820d' }
    - { index: 17, color: '0xc98344' }
    - { index: 18, color: '0x1c3657' }
    - { index: 19, color: '0x2a343a' }
    - { index: 20, color: '0x84898c' }
    - { index: 21, color: '0xa7cfa3' }
