# Base16 Horizon Terminal Light 256 - alacritty color config
# Michaël Ball (http://github.com/michael-ball/)
colors:
  # Default colors
  primary:
    background: '0xfdf0ed'
    foreground: '0x403c3d'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0xfdf0ed'
    cursor: '0x403c3d'

  # Normal colors
  normal:
    black:   '0xfdf0ed'
    red:     '0xe95678'
    green:   '0x29d398'
    yellow:  '0xfadad1'
    blue:    '0x26bbd9'
    magenta: '0xee64ac'
    cyan:    '0x59e1e3'
    white:   '0x403c3d'

  # Bright colors
  bright:
    black:   '0xbdb3b1'
    red:     '0xe95678'
    green:   '0x29d398'
    yellow:  '0xfadad1'
    blue:    '0x26bbd9'
    magenta: '0xee64ac'
    cyan:    '0x59e1e3'
    white:   '0x201c1d'

  indexed_colors:
    - { index: 16, color: '0xf9cec3' }
    - { index: 17, color: '0xf9cbbe' }
    - { index: 18, color: '0xfadad1' }
    - { index: 19, color: '0xf9cbbe' }
    - { index: 20, color: '0x948c8a' }
    - { index: 21, color: '0x302c2d' }
