# Base16 Default Light 256 - alacritty color config
# Chris Kempson (http://chriskempson.com)
colors:
  # Default colors
  primary:
    background: '0xf8f8f8'
    foreground: '0x383838'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0xf8f8f8'
    cursor: '0x383838'

  # Normal colors
  normal:
    black:   '0xf8f8f8'
    red:     '0xab4642'
    green:   '0xa1b56c'
    yellow:  '0xf7ca88'
    blue:    '0x7cafc2'
    magenta: '0xba8baf'
    cyan:    '0x86c1b9'
    white:   '0x383838'

  # Bright colors
  bright:
    black:   '0xb8b8b8'
    red:     '0xab4642'
    green:   '0xa1b56c'
    yellow:  '0xf7ca88'
    blue:    '0x7cafc2'
    magenta: '0xba8baf'
    cyan:    '0x86c1b9'
    white:   '0x181818'

  indexed_colors:
    - { index: 16, color: '0xdc9656' }
    - { index: 17, color: '0xa16946' }
    - { index: 18, color: '0xe8e8e8' }
    - { index: 19, color: '0xd8d8d8' }
    - { index: 20, color: '0x585858' }
    - { index: 21, color: '0x282828' }
