# Base16 Black Metal (Dark Funeral) - alacritty color config
# metalelf0 (https://github.com/metalelf0)
colors:
  # Default colors
  primary:
    background: '0x000000'
    foreground: '0xc1c1c1'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0x000000'
    cursor: '0xc1c1c1'

  # Normal colors
  normal:
    black:   '0x000000'
    red:     '0x5f8787'
    green:   '0xd0dfee'
    yellow:  '0x5f81a5'
    blue:    '0x888888'
    magenta: '0x999999'
    cyan:    '0xaaaaaa'
    white:   '0xc1c1c1'

  # Bright colors
  bright:
    black:   '0x333333'
    red:     '0xaaaaaa'
    green:   '0x121212'
    yellow:  '0x222222'
    blue:    '0x999999'
    magenta: '0x999999'
    cyan:    '0x444444'
    white:   '0xc1c1c1'

draw_bold_text_with_bright_colors: false
