# Base16 Gigavolt 256 - alacritty color config
# Aidan Swope (http://github.com/Whillikers)
colors:
  # Default colors
  primary:
    background: '0x202126'
    foreground: '0xe9e7e1'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0x202126'
    cursor: '0xe9e7e1'

  # Normal colors
  normal:
    black:   '0x202126'
    red:     '0xff661a'
    green:   '0xf2e6a9'
    yellow:  '0xffdc2d'
    blue:    '0x40bfff'
    magenta: '0xae94f9'
    cyan:    '0xfb6acb'
    white:   '0xe9e7e1'

  # Bright colors
  bright:
    black:   '0xa1d2e6'
    red:     '0xff661a'
    green:   '0xf2e6a9'
    yellow:  '0xffdc2d'
    blue:    '0x40bfff'
    magenta: '0xae94f9'
    cyan:    '0xfb6acb'
    white:   '0xf2fbff'

  indexed_colors:
    - { index: 16, color: '0x19f988' }
    - { index: 17, color: '0x6187ff' }
    - { index: 18, color: '0x2d303d' }
    - { index: 19, color: '0x5a576e' }
    - { index: 20, color: '0xcad3ff' }
    - { index: 21, color: '0xeff0f9' }
