# Base16 Tokyo City Light 256 - alacritty color config
# Michaël Ball
colors:
  # Default colors
  primary:
    background: '0xfbfbfd'
    foreground: '0x343b59'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0xfbfbfd'
    cursor: '0x343b59'

  # Normal colors
  normal:
    black:   '0xfbfbfd'
    red:     '0x8c4351'
    green:   '0x485e30'
    yellow:  '0x4c505e'
    blue:    '0x34548a'
    magenta: '0x5a4a78'
    cyan:    '0x4c505e'
    white:   '0x343b59'

  # Bright colors
  bright:
    black:   '0x9699a3'
    red:     '0x8c4351'
    green:   '0x485e30'
    yellow:  '0x4c505e'
    blue:    '0x34548a'
    magenta: '0x5a4a78'
    cyan:    '0x4c505e'
    white:   '0x171d23'

  indexed_colors:
    - { index: 16, color: '0x965027' }
    - { index: 17, color: '0x5a4a78' }
    - { index: 18, color: '0xf6f6f8' }
    - { index: 19, color: '0xedeff6' }
    - { index: 20, color: '0x4c505e' }
    - { index: 21, color: '0x1d252c' }
