# Base16 Qualia 256 - alacritty color config
# isaacwhanson
colors:
  # Default colors
  primary:
    background: '0x101010'
    foreground: '0xc0c0c0'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0x101010'
    cursor: '0xc0c0c0'

  # Normal colors
  normal:
    black:   '0x101010'
    red:     '0xefa6a2'
    green:   '0x80c990'
    yellow:  '0xe6a3dc'
    blue:    '0x50cacd'
    magenta: '0xe0af85'
    cyan:    '0xc8c874'
    white:   '0xc0c0c0'

  # Bright colors
  bright:
    black:   '0x454545'
    red:     '0xefa6a2'
    green:   '0x80c990'
    yellow:  '0xe6a3dc'
    blue:    '0x50cacd'
    magenta: '0xe0af85'
    cyan:    '0xc8c874'
    white:   '0x454545'

  indexed_colors:
    - { index: 16, color: '0xa3b8ef' }
    - { index: 17, color: '0x808080' }
    - { index: 18, color: '0x454545' }
    - { index: 19, color: '0x454545' }
    - { index: 20, color: '0x808080' }
    - { index: 21, color: '0xc0c0c0' }
