# Base16 Material - alacritty color config
# Nate Peterson
colors:
  # Default colors
  primary:
    background: '0x263238'
    foreground: '0xeeffff'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0x263238'
    cursor: '0xeeffff'

  # Normal colors
  normal:
    black:   '0x263238'
    red:     '0xf07178'
    green:   '0xc3e88d'
    yellow:  '0xffcb6b'
    blue:    '0x82aaff'
    magenta: '0xc792ea'
    cyan:    '0x89ddff'
    white:   '0xeeffff'

  # Bright colors
  bright:
    black:   '0x546e7a'
    red:     '0xf78c6c'
    green:   '0x2e3c43'
    yellow:  '0x314549'
    blue:    '0xb2ccd6'
    magenta: '0xeeffff'
    cyan:    '0xff5370'
    white:   '0xffffff'

draw_bold_text_with_bright_colors: false
