# Base16 Silk Dark - alacritty color config
# Gabriel Fontes (https://github.com/Misterio77)
colors:
  # Default colors
  primary:
    background: '0x0e3c46'
    foreground: '0xc7dbdd'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0x0e3c46'
    cursor: '0xc7dbdd'

  # Normal colors
  normal:
    black:   '0x0e3c46'
    red:     '0xfb6953'
    green:   '0x73d8ad'
    yellow:  '0xfce380'
    blue:    '0x46bddd'
    magenta: '0x756b8a'
    cyan:    '0x3fb2b9'
    white:   '0xc7dbdd'

  # Bright colors
  bright:
    black:   '0x587073'
    red:     '0xfcab74'
    green:   '0x1d494e'
    yellow:  '0x2a5054'
    blue:    '0x9dc8cd'
    magenta: '0xcbf2f7'
    cyan:    '0x9b647b'
    white:   '0xd2faff'

draw_bold_text_with_bright_colors: false
