# Base16 Dracula - alacritty color config
# Mike Barkmin (http://github.com/mikebarkmin) based on Dracula Theme (http://github.com/dracula)
colors:
  # Default colors
  primary:
    background: '0x282936'
    foreground: '0xe9e9f4'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0x282936'
    cursor: '0xe9e9f4'

  # Normal colors
  normal:
    black:   '0x282936'
    red:     '0xea51b2'
    green:   '0xebff87'
    yellow:  '0x00f769'
    blue:    '0x62d6e8'
    magenta: '0xb45bcf'
    cyan:    '0xa1efe4'
    white:   '0xe9e9f4'

  # Bright colors
  bright:
    black:   '0x626483'
    red:     '0xb45bcf'
    green:   '0x3a3c4e'
    yellow:  '0x4d4f68'
    blue:    '0x62d6e8'
    magenta: '0xf1f2f8'
    cyan:    '0x00f769'
    white:   '0xf7f7fb'

draw_bold_text_with_bright_colors: false
