# Base16 Harmonic16 Light 256 - alacritty color config
# Jannik Siebert (https://github.com/janniks)
colors:
  # Default colors
  primary:
    background: '0xf7f9fb'
    foreground: '0x405c79'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0xf7f9fb'
    cursor: '0x405c79'

  # Normal colors
  normal:
    black:   '0xf7f9fb'
    red:     '0xbf8b56'
    green:   '0x56bf8b'
    yellow:  '0x8bbf56'
    blue:    '0x8b56bf'
    magenta: '0xbf568b'
    cyan:    '0x568bbf'
    white:   '0x405c79'

  # Bright colors
  bright:
    black:   '0xaabcce'
    red:     '0xbf8b56'
    green:   '0x56bf8b'
    yellow:  '0x8bbf56'
    blue:    '0x8b56bf'
    magenta: '0xbf568b'
    cyan:    '0x568bbf'
    white:   '0x0b1c2c'

  indexed_colors:
    - { index: 16, color: '0xbfbf56' }
    - { index: 17, color: '0xbf5656' }
    - { index: 18, color: '0xe5ebf1' }
    - { index: 19, color: '0xcbd6e2' }
    - { index: 20, color: '0x627e99' }
    - { index: 21, color: '0x223b54' }
