# Base16 Atelier Sulphurpool - alacritty color config
# Bram de Haan (http://atelierbramdehaan.nl)
colors:
  # Default colors
  primary:
    background: '0x202746'
    foreground: '0x979db4'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0x202746'
    cursor: '0x979db4'

  # Normal colors
  normal:
    black:   '0x202746'
    red:     '0xc94922'
    green:   '0xac9739'
    yellow:  '0xc08b30'
    blue:    '0x3d8fd1'
    magenta: '0x6679cc'
    cyan:    '0x22a2c9'
    white:   '0x979db4'

  # Bright colors
  bright:
    black:   '0x6b7394'
    red:     '0xc76b29'
    green:   '0x293256'
    yellow:  '0x5e6687'
    blue:    '0x898ea4'
    magenta: '0xdfe2f1'
    cyan:    '0x9c637a'
    white:   '0xf5f7ff'

draw_bold_text_with_bright_colors: false
