# Base16 Atelier Plateau 256 - alacritty color config
# Bram de Haan (http://atelierbramdehaan.nl)
colors:
  # Default colors
  primary:
    background: '0x1b1818'
    foreground: '0x8a8585'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0x1b1818'
    cursor: '0x8a8585'

  # Normal colors
  normal:
    black:   '0x1b1818'
    red:     '0xca4949'
    green:   '0x4b8b8b'
    yellow:  '0xa06e3b'
    blue:    '0x7272ca'
    magenta: '0x8464c4'
    cyan:    '0x5485b6'
    white:   '0x8a8585'

  # Bright colors
  bright:
    black:   '0x655d5d'
    red:     '0xca4949'
    green:   '0x4b8b8b'
    yellow:  '0xa06e3b'
    blue:    '0x7272ca'
    magenta: '0x8464c4'
    cyan:    '0x5485b6'
    white:   '0xf4ecec'

  indexed_colors:
    - { index: 16, color: '0xb45a3c' }
    - { index: 17, color: '0xbd5187' }
    - { index: 18, color: '0x292424' }
    - { index: 19, color: '0x585050' }
    - { index: 20, color: '0x7e7777' }
    - { index: 21, color: '0xe7dfdf' }
