# Base16 Kimber - alacritty color config
# Mishka Nguyen (https://github.com/akhsiM)
colors:
  # Default colors
  primary:
    background: '0x222222'
    foreground: '0xdedee7'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0x222222'
    cursor: '0xdedee7'

  # Normal colors
  normal:
    black:   '0x222222'
    red:     '0xc88c8c'
    green:   '0x99c899'
    yellow:  '0xd8b56d'
    blue:    '0x537c9c'
    magenta: '0x86cacd'
    cyan:    '0x78b4b4'
    white:   '0xdedee7'

  # Bright colors
  bright:
    black:   '0x644646'
    red:     '0x476c88'
    green:   '0x313131'
    yellow:  '0x555d55'
    blue:    '0x5a5a5a'
    magenta: '0xc3c3b4'
    cyan:    '0x704f4f'
    white:   '0xffffe6'

draw_bold_text_with_bright_colors: false
