# Base16 Tokyo Night Terminal Light - alacritty color config
# Michaël Ball
colors:
  # Default colors
  primary:
    background: '0xd5d6db'
    foreground: '0x4c505e'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0xd5d6db'
    cursor: '0x4c505e'

  # Normal colors
  normal:
    black:   '0xd5d6db'
    red:     '0x8c4351'
    green:   '0x33635c'
    yellow:  '0x8f5e15'
    blue:    '0x34548a'
    magenta: '0x5a4a78'
    cyan:    '0x0f4b6e'
    white:   '0x4c505e'

  # Bright colors
  bright:
    black:   '0x9699a3'
    red:     '0x965027'
    green:   '0xcbccd1'
    yellow:  '0xdfe0e5'
    blue:    '0x4c505e'
    magenta: '0x1a1b26'
    cyan:    '0x655259'
    white:   '0x1a1b26'

draw_bold_text_with_bright_colors: false
