# Base16 Atelier Cave Light 256 - alacritty color config
# Bram de Haan (http://atelierbramdehaan.nl)
colors:
  # Default colors
  primary:
    background: '0xefecf4'
    foreground: '0x585260'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0xefecf4'
    cursor: '0x585260'

  # Normal colors
  normal:
    black:   '0xefecf4'
    red:     '0xbe4678'
    green:   '0x2a9292'
    yellow:  '0xa06e3b'
    blue:    '0x576ddb'
    magenta: '0x955ae7'
    cyan:    '0x398bc6'
    white:   '0x585260'

  # Bright colors
  bright:
    black:   '0x7e7887'
    red:     '0xbe4678'
    green:   '0x2a9292'
    yellow:  '0xa06e3b'
    blue:    '0x576ddb'
    magenta: '0x955ae7'
    cyan:    '0x398bc6'
    white:   '0x19171c'

  indexed_colors:
    - { index: 16, color: '0xaa573c' }
    - { index: 17, color: '0xbf40bf' }
    - { index: 18, color: '0xe2dfe7' }
    - { index: 19, color: '0x8b8792' }
    - { index: 20, color: '0x655f6d' }
    - { index: 21, color: '0x26232a' }
