# Base16 Gruvbox dark, pale 256 - alacritty color config
# Dawid Kurek (dawikur@gmail.com), morhetz (https://github.com/morhetz/gruvbox)
colors:
  # Default colors
  primary:
    background: '0x262626'
    foreground: '0xdab997'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0x262626'
    cursor: '0xdab997'

  # Normal colors
  normal:
    black:   '0x262626'
    red:     '0xd75f5f'
    green:   '0xafaf00'
    yellow:  '0xffaf00'
    blue:    '0x83adad'
    magenta: '0xd485ad'
    cyan:    '0x85ad85'
    white:   '0xdab997'

  # Bright colors
  bright:
    black:   '0x8a8a8a'
    red:     '0xd75f5f'
    green:   '0xafaf00'
    yellow:  '0xffaf00'
    blue:    '0x83adad'
    magenta: '0xd485ad'
    cyan:    '0x85ad85'
    white:   '0xebdbb2'

  indexed_colors:
    - { index: 16, color: '0xff8700' }
    - { index: 17, color: '0xd65d0e' }
    - { index: 18, color: '0x3a3a3a' }
    - { index: 19, color: '0x4e4e4e' }
    - { index: 20, color: '0x949494' }
    - { index: 21, color: '0xd5c4a1' }
