# Base16 Unikitty Dark 256 - alacritty color config
# Josh W Lewis (@joshwlewis)
colors:
  # Default colors
  primary:
    background: '0x2e2a31'
    foreground: '0xbcbabe'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0x2e2a31'
    cursor: '0xbcbabe'

  # Normal colors
  normal:
    black:   '0x2e2a31'
    red:     '0xd8137f'
    green:   '0x17ad98'
    yellow:  '0xdc8a0e'
    blue:    '0x796af5'
    magenta: '0xbb60ea'
    cyan:    '0x149bda'
    white:   '0xbcbabe'

  # Bright colors
  bright:
    black:   '0x838085'
    red:     '0xd8137f'
    green:   '0x17ad98'
    yellow:  '0xdc8a0e'
    blue:    '0x796af5'
    magenta: '0xbb60ea'
    cyan:    '0x149bda'
    white:   '0xf5f4f7'

  indexed_colors:
    - { index: 16, color: '0xd65407' }
    - { index: 17, color: '0xc720ca' }
    - { index: 18, color: '0x4a464d' }
    - { index: 19, color: '0x666369' }
    - { index: 20, color: '0x9f9da2' }
    - { index: 21, color: '0xd8d7da' }
