# Base16 Hopscotch 256 - alacritty color config
# Jan T. Sott
colors:
  # Default colors
  primary:
    background: '0x322931'
    foreground: '0xb9b5b8'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0x322931'
    cursor: '0xb9b5b8'

  # Normal colors
  normal:
    black:   '0x322931'
    red:     '0xdd464c'
    green:   '0x8fc13e'
    yellow:  '0xfdcc59'
    blue:    '0x1290bf'
    magenta: '0xc85e7c'
    cyan:    '0x149b93'
    white:   '0xb9b5b8'

  # Bright colors
  bright:
    black:   '0x797379'
    red:     '0xdd464c'
    green:   '0x8fc13e'
    yellow:  '0xfdcc59'
    blue:    '0x1290bf'
    magenta: '0xc85e7c'
    cyan:    '0x149b93'
    white:   '0xffffff'

  indexed_colors:
    - { index: 16, color: '0xfd8b19' }
    - { index: 17, color: '0xb33508' }
    - { index: 18, color: '0x433b42' }
    - { index: 19, color: '0x5c545b' }
    - { index: 20, color: '0x989498' }
    - { index: 21, color: '0xd5d3d5' }
