# Base16 Isotope - alacritty color config
# Jan T. Sott
colors:
  # Default colors
  primary:
    background: '0x000000'
    foreground: '0xd0d0d0'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0x000000'
    cursor: '0xd0d0d0'

  # Normal colors
  normal:
    black:   '0x000000'
    red:     '0xff0000'
    green:   '0x33ff00'
    yellow:  '0xff0099'
    blue:    '0x0066ff'
    magenta: '0xcc00ff'
    cyan:    '0x00ffff'
    white:   '0xd0d0d0'

  # Bright colors
  bright:
    black:   '0x808080'
    red:     '0xff9900'
    green:   '0x404040'
    yellow:  '0x606060'
    blue:    '0xc0c0c0'
    magenta: '0xe0e0e0'
    cyan:    '0x3300ff'
    white:   '0xffffff'

draw_bold_text_with_bright_colors: false
