# Base16 Pico - alacritty color config
# PICO-8 (http://www.lexaloffle.com/pico-8.php)
colors:
  # Default colors
  primary:
    background: '0x000000'
    foreground: '0x5f574f'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0x000000'
    cursor: '0x5f574f'

  # Normal colors
  normal:
    black:   '0x000000'
    red:     '0xff004d'
    green:   '0x00e756'
    yellow:  '0xfff024'
    blue:    '0x83769c'
    magenta: '0xff77a8'
    cyan:    '0x29adff'
    white:   '0x5f574f'

  # Bright colors
  bright:
    black:   '0x008751'
    red:     '0xffa300'
    green:   '0x1d2b53'
    yellow:  '0x7e2553'
    blue:    '0xab5236'
    magenta: '0xc2c3c7'
    cyan:    '0xffccaa'
    white:   '0xfff1e8'

draw_bold_text_with_bright_colors: false
