# Base16 Atelier Forest Light 256 - alacritty color config
# Bram de Haan (http://atelierbramdehaan.nl)
colors:
  # Default colors
  primary:
    background: '0xf1efee'
    foreground: '0x68615e'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0xf1efee'
    cursor: '0x68615e'

  # Normal colors
  normal:
    black:   '0xf1efee'
    red:     '0xf22c40'
    green:   '0x7b9726'
    yellow:  '0xc38418'
    blue:    '0x407ee7'
    magenta: '0x6666ea'
    cyan:    '0x3d97b8'
    white:   '0x68615e'

  # Bright colors
  bright:
    black:   '0x9c9491'
    red:     '0xf22c40'
    green:   '0x7b9726'
    yellow:  '0xc38418'
    blue:    '0x407ee7'
    magenta: '0x6666ea'
    cyan:    '0x3d97b8'
    white:   '0x1b1918'

  indexed_colors:
    - { index: 16, color: '0xdf5320' }
    - { index: 17, color: '0xc33ff3' }
    - { index: 18, color: '0xe6e2e0' }
    - { index: 19, color: '0xa8a19f' }
    - { index: 20, color: '0x766e6b' }
    - { index: 21, color: '0x2c2421' }
