# Base16 Hopscotch - alacritty color config
# Jan T. Sott
colors:
  # Default colors
  primary:
    background: '0x322931'
    foreground: '0xb9b5b8'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0x322931'
    cursor: '0xb9b5b8'

  # Normal colors
  normal:
    black:   '0x322931'
    red:     '0xdd464c'
    green:   '0x8fc13e'
    yellow:  '0xfdcc59'
    blue:    '0x1290bf'
    magenta: '0xc85e7c'
    cyan:    '0x149b93'
    white:   '0xb9b5b8'

  # Bright colors
  bright:
    black:   '0x797379'
    red:     '0xfd8b19'
    green:   '0x433b42'
    yellow:  '0x5c545b'
    blue:    '0x989498'
    magenta: '0xd5d3d5'
    cyan:    '0xb33508'
    white:   '0xffffff'

draw_bold_text_with_bright_colors: false
