# Base16 Dark Violet - alacritty color config
# ruler501 (https://github.com/ruler501/base16-darkviolet)
colors:
  # Default colors
  primary:
    background: '0x000000'
    foreground: '0xb08ae6'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0x000000'
    cursor: '0xb08ae6'

  # Normal colors
  normal:
    black:   '0x000000'
    red:     '0xa82ee6'
    green:   '0x4595e6'
    yellow:  '0xf29df2'
    blue:    '0x4136d9'
    magenta: '0x7e5ce6'
    cyan:    '0x40dfff'
    white:   '0xb08ae6'

  # Bright colors
  bright:
    black:   '0x593380'
    red:     '0xbb66cc'
    green:   '0x231a40'
    yellow:  '0x432d59'
    blue:    '0x00ff00'
    magenta: '0x9045e6'
    cyan:    '0xa886bf'
    white:   '0xa366ff'

draw_bold_text_with_bright_colors: false
