# Base16 Horizon Terminal Dark - alacritty color config
# Michaël Ball (http://github.com/michael-ball/)
colors:
  # Default colors
  primary:
    background: '0x1c1e26'
    foreground: '0xcbced0'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0x1c1e26'
    cursor: '0xcbced0'

  # Normal colors
  normal:
    black:   '0x1c1e26'
    red:     '0xe95678'
    green:   '0x29d398'
    yellow:  '0xfac29a'
    blue:    '0x26bbd9'
    magenta: '0xee64ac'
    cyan:    '0x59e1e3'
    white:   '0xcbced0'

  # Bright colors
  bright:
    black:   '0x6f6f70'
    red:     '0xfab795'
    green:   '0x232530'
    yellow:  '0x2e303e'
    blue:    '0x9da0a2'
    magenta: '0xdcdfe4'
    cyan:    '0xf09383'
    white:   '0xe3e6ee'

draw_bold_text_with_bright_colors: false
