# Base16 Zenburn - alacritty color config
# elnawe
colors:
  # Default colors
  primary:
    background: '0x383838'
    foreground: '0xdcdccc'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0x383838'
    cursor: '0xdcdccc'

  # Normal colors
  normal:
    black:   '0x383838'
    red:     '0xdca3a3'
    green:   '0x5f7f5f'
    yellow:  '0xe0cf9f'
    blue:    '0x7cb8bb'
    magenta: '0xdc8cc3'
    cyan:    '0x93e0e3'
    white:   '0xdcdccc'

  # Bright colors
  bright:
    black:   '0x6f6f6f'
    red:     '0xdfaf8f'
    green:   '0x404040'
    yellow:  '0x606060'
    blue:    '0x808080'
    magenta: '0xc0c0c0'
    cyan:    '0x000000'
    white:   '0xffffff'

draw_bold_text_with_bright_colors: false
