# Base16 Hardcore - alacritty color config
# Chris Caller
colors:
  # Default colors
  primary:
    background: '0x212121'
    foreground: '0xcdcdcd'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0x212121'
    cursor: '0xcdcdcd'

  # Normal colors
  normal:
    black:   '0x212121'
    red:     '0xf92672'
    green:   '0xa6e22e'
    yellow:  '0xe6db74'
    blue:    '0x66d9ef'
    magenta: '0x9e6ffe'
    cyan:    '0x708387'
    white:   '0xcdcdcd'

  # Bright colors
  bright:
    black:   '0x4a4a4a'
    red:     '0xfd971f'
    green:   '0x303030'
    yellow:  '0x353535'
    blue:    '0x707070'
    magenta: '0xe5e5e5'
    cyan:    '0xe8b882'
    white:   '0xffffff'

draw_bold_text_with_bright_colors: false
