# Base16 Pico 256 - alacritty color config
# PICO-8 (http://www.lexaloffle.com/pico-8.php)
colors:
  # Default colors
  primary:
    background: '0x000000'
    foreground: '0x5f574f'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0x000000'
    cursor: '0x5f574f'

  # Normal colors
  normal:
    black:   '0x000000'
    red:     '0xff004d'
    green:   '0x00e756'
    yellow:  '0xfff024'
    blue:    '0x83769c'
    magenta: '0xff77a8'
    cyan:    '0x29adff'
    white:   '0x5f574f'

  # Bright colors
  bright:
    black:   '0x008751'
    red:     '0xff004d'
    green:   '0x00e756'
    yellow:  '0xfff024'
    blue:    '0x83769c'
    magenta: '0xff77a8'
    cyan:    '0x29adff'
    white:   '0xfff1e8'

  indexed_colors:
    - { index: 16, color: '0xffa300' }
    - { index: 17, color: '0xffccaa' }
    - { index: 18, color: '0x1d2b53' }
    - { index: 19, color: '0x7e2553' }
    - { index: 20, color: '0xab5236' }
    - { index: 21, color: '0xc2c3c7' }
