# Base16 Apathy 256 - alacritty color config
# Jannik Siebert (https://github.com/janniks)
colors:
  # Default colors
  primary:
    background: '0x031a16'
    foreground: '0x81b5ac'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0x031a16'
    cursor: '0x81b5ac'

  # Normal colors
  normal:
    black:   '0x031a16'
    red:     '0x3e9688'
    green:   '0x883e96'
    yellow:  '0x3e4c96'
    blue:    '0x96883e'
    magenta: '0x4c963e'
    cyan:    '0x963e4c'
    white:   '0x81b5ac'

  # Bright colors
  bright:
    black:   '0x2b685e'
    red:     '0x3e9688'
    green:   '0x883e96'
    yellow:  '0x3e4c96'
    blue:    '0x96883e'
    magenta: '0x4c963e'
    cyan:    '0x963e4c'
    white:   '0xd2e7e4'

  indexed_colors:
    - { index: 16, color: '0x3e7996' }
    - { index: 17, color: '0x3e965b' }
    - { index: 18, color: '0x0b342d' }
    - { index: 19, color: '0x184e45' }
    - { index: 20, color: '0x5f9c92' }
    - { index: 21, color: '0xa7cec8' }
