# Base16 Helios 256 - alacritty color config
# Alex Meyer (https://github.com/reyemxela)
colors:
  # Default colors
  primary:
    background: '0x1d2021'
    foreground: '0xd5d5d5'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0x1d2021'
    cursor: '0xd5d5d5'

  # Normal colors
  normal:
    black:   '0x1d2021'
    red:     '0xd72638'
    green:   '0x88b92d'
    yellow:  '0xf19d1a'
    blue:    '0x1e8bac'
    magenta: '0xbe4264'
    cyan:    '0x1ba595'
    white:   '0xd5d5d5'

  # Bright colors
  bright:
    black:   '0x6f7579'
    red:     '0xd72638'
    green:   '0x88b92d'
    yellow:  '0xf19d1a'
    blue:    '0x1e8bac'
    magenta: '0xbe4264'
    cyan:    '0x1ba595'
    white:   '0xe5e5e5'

  indexed_colors:
    - { index: 16, color: '0xeb8413' }
    - { index: 17, color: '0xc85e0d' }
    - { index: 18, color: '0x383c3e' }
    - { index: 19, color: '0x53585b' }
    - { index: 20, color: '0xcdcdcd' }
    - { index: 21, color: '0xdddddd' }
