# Base16 PhD - alacritty color config
# Hennig Hasemann (http://leetless.de/vim.html)
colors:
  # Default colors
  primary:
    background: '0x061229'
    foreground: '0xb8bbc2'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0x061229'
    cursor: '0xb8bbc2'

  # Normal colors
  normal:
    black:   '0x061229'
    red:     '0xd07346'
    green:   '0x99bf52'
    yellow:  '0xfbd461'
    blue:    '0x5299bf'
    magenta: '0x9989cc'
    cyan:    '0x72b9bf'
    white:   '0xb8bbc2'

  # Bright colors
  bright:
    black:   '0x717885'
    red:     '0xf0a000'
    green:   '0x2a3448'
    yellow:  '0x4d5666'
    blue:    '0x9a99a3'
    magenta: '0xdbdde0'
    cyan:    '0xb08060'
    white:   '0xffffff'

draw_bold_text_with_bright_colors: false
