# Base16 Spacemacs - alacritty color config
# Nasser Alshammari (https://github.com/nashamri/spacemacs-theme)
colors:
  # Default colors
  primary:
    background: '0x1f2022'
    foreground: '0xa3a3a3'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0x1f2022'
    cursor: '0xa3a3a3'

  # Normal colors
  normal:
    black:   '0x1f2022'
    red:     '0xf2241f'
    green:   '0x67b11d'
    yellow:  '0xb1951d'
    blue:    '0x4f97d7'
    magenta: '0xa31db1'
    cyan:    '0x2d9574'
    white:   '0xa3a3a3'

  # Bright colors
  bright:
    black:   '0x585858'
    red:     '0xffa500'
    green:   '0x282828'
    yellow:  '0x444155'
    blue:    '0xb8b8b8'
    magenta: '0xe8e8e8'
    cyan:    '0xb03060'
    white:   '0xf8f8f8'

draw_bold_text_with_bright_colors: false
