# Base16 Macintosh 256 - alacritty color config
# Rebecca Bettencourt (http://www.kreativekorp.com)
colors:
  # Default colors
  primary:
    background: '0x000000'
    foreground: '0xc0c0c0'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0x000000'
    cursor: '0xc0c0c0'

  # Normal colors
  normal:
    black:   '0x000000'
    red:     '0xdd0907'
    green:   '0x1fb714'
    yellow:  '0xfbf305'
    blue:    '0x0000d3'
    magenta: '0x4700a5'
    cyan:    '0x02abea'
    white:   '0xc0c0c0'

  # Bright colors
  bright:
    black:   '0x808080'
    red:     '0xdd0907'
    green:   '0x1fb714'
    yellow:  '0xfbf305'
    blue:    '0x0000d3'
    magenta: '0x4700a5'
    cyan:    '0x02abea'
    white:   '0xffffff'

  indexed_colors:
    - { index: 16, color: '0xff6403' }
    - { index: 17, color: '0x90713a' }
    - { index: 18, color: '0x404040' }
    - { index: 19, color: '0x404040' }
    - { index: 20, color: '0x808080' }
    - { index: 21, color: '0xc0c0c0' }
