# Base16 Tokyo Night Light 256 - alacritty color config
# Michaël Ball
colors:
  # Default colors
  primary:
    background: '0xd5d6db'
    foreground: '0x343b59'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0xd5d6db'
    cursor: '0x343b59'

  # Normal colors
  normal:
    black:   '0xd5d6db'
    red:     '0x343b58'
    green:   '0x485e30'
    yellow:  '0x166775'
    blue:    '0x34548a'
    magenta: '0x5a4a78'
    cyan:    '0x3e6968'
    white:   '0x343b59'

  # Bright colors
  bright:
    black:   '0x9699a3'
    red:     '0x343b58'
    green:   '0x485e30'
    yellow:  '0x166775'
    blue:    '0x34548a'
    magenta: '0x5a4a78'
    cyan:    '0x3e6968'
    white:   '0x1a1b26'

  indexed_colors:
    - { index: 16, color: '0x965027' }
    - { index: 17, color: '0x8c4351' }
    - { index: 18, color: '0xcbccd1' }
    - { index: 19, color: '0xdfe0e5' }
    - { index: 20, color: '0x4c505e' }
    - { index: 21, color: '0x1a1b26' }
