# Base16 selenized-white 256 - alacritty color config
# Jan Warchol (https://github.com/jan-warchol/selenized) / adapted to base16 by ali
colors:
  # Default colors
  primary:
    background: '0xffffff'
    foreground: '0x474747'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0xffffff'
    cursor: '0x474747'

  # Normal colors
  normal:
    black:   '0xffffff'
    red:     '0xbf0000'
    green:   '0x008400'
    yellow:  '0xaf8500'
    blue:    '0x0054cf'
    magenta: '0x6b40c3'
    cyan:    '0x009a8a'
    white:   '0x474747'

  # Bright colors
  bright:
    black:   '0x878787'
    red:     '0xbf0000'
    green:   '0x008400'
    yellow:  '0xaf8500'
    blue:    '0x0054cf'
    magenta: '0x6b40c3'
    cyan:    '0x009a8a'
    white:   '0x282828'

  indexed_colors:
    - { index: 16, color: '0xba3700' }
    - { index: 17, color: '0xdd0f9d' }
    - { index: 18, color: '0xebebeb' }
    - { index: 19, color: '0xcdcdcd' }
    - { index: 20, color: '0x878787' }
    - { index: 21, color: '0x282828' }
