# Base16 Heetch Dark - alacritty color config
# Geoffrey Teale (tealeg@gmail.com)
colors:
  # Default colors
  primary:
    background: '0x190134'
    foreground: '0xbdb6c5'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0x190134'
    cursor: '0xbdb6c5'

  # Normal colors
  normal:
    black:   '0x190134'
    red:     '0x27d9d5'
    green:   '0xc33678'
    yellow:  '0x8f6c97'
    blue:    '0xbd0152'
    magenta: '0x82034c'
    cyan:    '0xf80059'
    white:   '0xbdb6c5'

  # Bright colors
  bright:
    black:   '0x7b6d8b'
    red:     '0x5ba2b6'
    green:   '0x392551'
    yellow:  '0x5a496e'
    blue:    '0x9c92a8'
    magenta: '0xdedae2'
    cyan:    '0x470546'
    white:   '0xfeffff'

draw_bold_text_with_bright_colors: false
