# Base16 Icy Dark 256 - alacritty color config
# icyphox (https://icyphox.ga)
colors:
  # Default colors
  primary:
    background: '0x021012'
    foreground: '0x095b67'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0x021012'
    cursor: '0x095b67'

  # Normal colors
  normal:
    black:   '0x021012'
    red:     '0x16c1d9'
    green:   '0x4dd0e1'
    yellow:  '0x80deea'
    blue:    '0x00bcd4'
    magenta: '0x00acc1'
    cyan:    '0x26c6da'
    white:   '0x095b67'

  # Bright colors
  bright:
    black:   '0x052e34'
    red:     '0x16c1d9'
    green:   '0x4dd0e1'
    yellow:  '0x80deea'
    blue:    '0x00bcd4'
    magenta: '0x00acc1'
    cyan:    '0x26c6da'
    white:   '0x109cb0'

  indexed_colors:
    - { index: 16, color: '0xb3ebf2' }
    - { index: 17, color: '0x0097a7' }
    - { index: 18, color: '0x031619' }
    - { index: 19, color: '0x041f23' }
    - { index: 20, color: '0x064048' }
    - { index: 21, color: '0x0c7c8c' }
