# Base16 Atelier Lakeside - alacritty color config
# Bram de Haan (http://atelierbramdehaan.nl)
colors:
  # Default colors
  primary:
    background: '0x161b1d'
    foreground: '0x7ea2b4'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0x161b1d'
    cursor: '0x7ea2b4'

  # Normal colors
  normal:
    black:   '0x161b1d'
    red:     '0xd22d72'
    green:   '0x568c3b'
    yellow:  '0x8a8a0f'
    blue:    '0x257fad'
    magenta: '0x6b6bb8'
    cyan:    '0x2d8f6f'
    white:   '0x7ea2b4'

  # Bright colors
  bright:
    black:   '0x5a7b8c'
    red:     '0x935c25'
    green:   '0x1f292e'
    yellow:  '0x516d7b'
    blue:    '0x7195a8'
    magenta: '0xc1e4f6'
    cyan:    '0xb72dd2'
    white:   '0xebf8ff'

draw_bold_text_with_bright_colors: false
