# Base16 Gigavolt - alacritty color config
# Aidan Swope (http://github.com/Whillikers)
colors:
  # Default colors
  primary:
    background: '0x202126'
    foreground: '0xe9e7e1'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0x202126'
    cursor: '0xe9e7e1'

  # Normal colors
  normal:
    black:   '0x202126'
    red:     '0xff661a'
    green:   '0xf2e6a9'
    yellow:  '0xffdc2d'
    blue:    '0x40bfff'
    magenta: '0xae94f9'
    cyan:    '0xfb6acb'
    white:   '0xe9e7e1'

  # Bright colors
  bright:
    black:   '0xa1d2e6'
    red:     '0x19f988'
    green:   '0x2d303d'
    yellow:  '0x5a576e'
    blue:    '0xcad3ff'
    magenta: '0xeff0f9'
    cyan:    '0x6187ff'
    white:   '0xf2fbff'

draw_bold_text_with_bright_colors: false
