# Base16 Shapeshifter 256 - alacritty color config
# Tyler Benziger (http://tybenz.com)
colors:
  # Default colors
  primary:
    background: '0xf9f9f9'
    foreground: '0x102015'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0xf9f9f9'
    cursor: '0x102015'

  # Normal colors
  normal:
    black:   '0xf9f9f9'
    red:     '0xe92f2f'
    green:   '0x0ed839'
    yellow:  '0xdddd13'
    blue:    '0x3b48e3'
    magenta: '0xf996e2'
    cyan:    '0x23edda'
    white:   '0x102015'

  # Bright colors
  bright:
    black:   '0x555555'
    red:     '0xe92f2f'
    green:   '0x0ed839'
    yellow:  '0xdddd13'
    blue:    '0x3b48e3'
    magenta: '0xf996e2'
    cyan:    '0x23edda'
    white:   '0x000000'

  indexed_colors:
    - { index: 16, color: '0xe09448' }
    - { index: 17, color: '0x69542d' }
    - { index: 18, color: '0xe0e0e0' }
    - { index: 19, color: '0xababab' }
    - { index: 20, color: '0x343434' }
    - { index: 21, color: '0x040404' }
