# Base16 Fruit Soda - alacritty color config
# jozip
colors:
  # Default colors
  primary:
    background: '0xf1ecf1'
    foreground: '0x515151'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0xf1ecf1'
    cursor: '0x515151'

  # Normal colors
  normal:
    black:   '0xf1ecf1'
    red:     '0xfe3e31'
    green:   '0x47f74c'
    yellow:  '0xf7e203'
    blue:    '0x2931df'
    magenta: '0x611fce'
    cyan:    '0x0f9cfd'
    white:   '0x515151'

  # Bright colors
  bright:
    black:   '0xb5b4b6'
    red:     '0xfe6d08'
    green:   '0xe0dee0'
    yellow:  '0xd8d5d5'
    blue:    '0x979598'
    magenta: '0x474545'
    cyan:    '0xb16f40'
    white:   '0x2d2c2c'

draw_bold_text_with_bright_colors: false
