# Base16 Equilibrium Light 256 - alacritty color config
# Carlo Abelli
colors:
  # Default colors
  primary:
    background: '0xf5f0e7'
    foreground: '0x43474e'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0xf5f0e7'
    cursor: '0x43474e'

  # Normal colors
  normal:
    black:   '0xf5f0e7'
    red:     '0xd02023'
    green:   '0x637200'
    yellow:  '0x9d6f00'
    blue:    '0x0073b5'
    magenta: '0x4e66b6'
    cyan:    '0x007a72'
    white:   '0x43474e'

  # Bright colors
  bright:
    black:   '0x73777f'
    red:     '0xd02023'
    green:   '0x637200'
    yellow:  '0x9d6f00'
    blue:    '0x0073b5'
    magenta: '0x4e66b6'
    cyan:    '0x007a72'
    white:   '0x181c22'

  indexed_colors:
    - { index: 16, color: '0xbf3e05' }
    - { index: 17, color: '0xc42775' }
    - { index: 18, color: '0xe7e2d9' }
    - { index: 19, color: '0xd8d4cb' }
    - { index: 20, color: '0x5a5f66' }
    - { index: 21, color: '0x2c3138' }
