# Base16 Horizon Terminal Light - alacritty color config
# Michaël Ball (http://github.com/michael-ball/)
colors:
  # Default colors
  primary:
    background: '0xfdf0ed'
    foreground: '0x403c3d'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0xfdf0ed'
    cursor: '0x403c3d'

  # Normal colors
  normal:
    black:   '0xfdf0ed'
    red:     '0xe95678'
    green:   '0x29d398'
    yellow:  '0xfadad1'
    blue:    '0x26bbd9'
    magenta: '0xee64ac'
    cyan:    '0x59e1e3'
    white:   '0x403c3d'

  # Bright colors
  bright:
    black:   '0xbdb3b1'
    red:     '0xf9cec3'
    green:   '0xfadad1'
    yellow:  '0xf9cbbe'
    blue:    '0x948c8a'
    magenta: '0x302c2d'
    cyan:    '0xf9cbbe'
    white:   '0x201c1d'

draw_bold_text_with_bright_colors: false
