# Base16 ShadeSmear Light 256 - alacritty color config
# Kyle Giammarco (http://kyle.giammar.co)
colors:
  # Default colors
  primary:
    background: '0xdbdbdb'
    foreground: '0x232323'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0xdbdbdb'
    cursor: '0x232323'

  # Normal colors
  normal:
    black:   '0xdbdbdb'
    red:     '0xcc5450'
    green:   '0x71983b'
    yellow:  '0x307878'
    blue:    '0x376388'
    magenta: '0xd7ab54'
    cyan:    '0xc57d42'
    white:   '0x232323'

  # Bright colors
  bright:
    black:   '0x4e4e4e'
    red:     '0xcc5450'
    green:   '0x71983b'
    yellow:  '0x307878'
    blue:    '0x376388'
    magenta: '0xd7ab54'
    cyan:    '0xc57d42'
    white:   '0xe4e4e4'

  indexed_colors:
    - { index: 16, color: '0xa64270' }
    - { index: 17, color: '0x6d6d6d' }
    - { index: 18, color: '0xe4e4e4' }
    - { index: 19, color: '0xc0c0c0' }
    - { index: 20, color: '0x1c1c1c' }
    - { index: 21, color: '0x1c1c1c' }
