# Base16 Heetch Light - alacritty color config
# Geoffrey Teale (tealeg@gmail.com)
colors:
  # Default colors
  primary:
    background: '0xfeffff'
    foreground: '0x5a496e'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0xfeffff'
    cursor: '0x5a496e'

  # Normal colors
  normal:
    black:   '0xfeffff'
    red:     '0x27d9d5'
    green:   '0xf80059'
    yellow:  '0x5ba2b6'
    blue:    '0x47f9f5'
    magenta: '0xbd0152'
    cyan:    '0xc33678'
    white:   '0x5a496e'

  # Bright colors
  bright:
    black:   '0x9c92a8'
    red:     '0xbdb6c5'
    green:   '0x392551'
    yellow:  '0x7b6d8b'
    blue:    '0xddd6e5'
    magenta: '0x470546'
    cyan:    '0xdedae2'
    white:   '0x190134'

draw_bold_text_with_bright_colors: false
