# Base16 Blueish 256 - alacritty color config
# Ben Mayoras
colors:
  # Default colors
  primary:
    background: '0x182430'
    foreground: '0xc8e1f8'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0x182430'
    cursor: '0xc8e1f8'

  # Normal colors
  normal:
    black:   '0x182430'
    red:     '0x4ce587'
    green:   '0xc3e88d'
    yellow:  '0x82aaff'
    blue:    '0x82aaff'
    magenta: '0xff84dd'
    cyan:    '0x5fd1ff'
    white:   '0xc8e1f8'

  # Bright colors
  bright:
    black:   '0x616d78'
    red:     '0x4ce587'
    green:   '0xc3e88d'
    yellow:  '0x82aaff'
    blue:    '0x82aaff'
    magenta: '0xff84dd'
    cyan:    '0x5fd1ff'
    white:   '0x8f98a0'

  indexed_colors:
    - { index: 16, color: '0xf6a85c' }
    - { index: 17, color: '0xbbd2e8' }
    - { index: 18, color: '0x243c54' }
    - { index: 19, color: '0x46290a' }
    - { index: 20, color: '0x74afe7' }
    - { index: 21, color: '0xddeaf6' }
