# Base16 Cupertino - alacritty color config
# Defman21
colors:
  # Default colors
  primary:
    background: '0xffffff'
    foreground: '0x404040'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0xffffff'
    cursor: '0x404040'

  # Normal colors
  normal:
    black:   '0xffffff'
    red:     '0xc41a15'
    green:   '0x007400'
    yellow:  '0x826b28'
    blue:    '0x0000ff'
    magenta: '0xa90d91'
    cyan:    '0x318495'
    white:   '0x404040'

  # Bright colors
  bright:
    black:   '0x808080'
    red:     '0xeb8500'
    green:   '0xc0c0c0'
    yellow:  '0xc0c0c0'
    blue:    '0x808080'
    magenta: '0x404040'
    cyan:    '0x826b28'
    white:   '0x5e5e5e'

draw_bold_text_with_bright_colors: false
