# Base16 Gotham 256 - alacritty color config
# Andrea Leopardi (arranged by Brett Jones)
colors:
  # Default colors
  primary:
    background: '0x0c1014'
    foreground: '0x599cab'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0x0c1014'
    cursor: '0x599cab'

  # Normal colors
  normal:
    black:   '0x0c1014'
    red:     '0xc23127'
    green:   '0x33859e'
    yellow:  '0xedb443'
    blue:    '0x195466'
    magenta: '0x888ca6'
    cyan:    '0x2aa889'
    white:   '0x599cab'

  # Bright colors
  bright:
    black:   '0x0a3749'
    red:     '0xc23127'
    green:   '0x33859e'
    yellow:  '0xedb443'
    blue:    '0x195466'
    magenta: '0x888ca6'
    cyan:    '0x2aa889'
    white:   '0xd3ebe9'

  indexed_colors:
    - { index: 16, color: '0xd26937' }
    - { index: 17, color: '0x4e5166' }
    - { index: 18, color: '0x11151c' }
    - { index: 19, color: '0x091f2e' }
    - { index: 20, color: '0x245361' }
    - { index: 21, color: '0x99d1ce' }
