# Base16 Tokyo City Terminal Light - alacritty color config
# Michaël Ball
colors:
  # Default colors
  primary:
    background: '0xfbfbfd'
    foreground: '0x28323a'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0xfbfbfd'
    cursor: '0x28323a'

  # Normal colors
  normal:
    black:   '0xfbfbfd'
    red:     '0x8c4351'
    green:   '0x33635c'
    yellow:  '0x8f5e15'
    blue:    '0x34548a'
    magenta: '0x5a4a78'
    cyan:    '0x0f4b6e'
    white:   '0x28323a'

  # Bright colors
  bright:
    black:   '0xb7c5d3'
    red:     '0x965027'
    green:   '0xf6f6f8'
    yellow:  '0xd8e2ec'
    blue:    '0x526270'
    magenta: '0x1d252c'
    cyan:    '0x7e5140'
    white:   '0x171d23'

draw_bold_text_with_bright_colors: false
