# Base16 Macintosh - alacritty color config
# Rebecca Bettencourt (http://www.kreativekorp.com)
colors:
  # Default colors
  primary:
    background: '0x000000'
    foreground: '0xc0c0c0'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0x000000'
    cursor: '0xc0c0c0'

  # Normal colors
  normal:
    black:   '0x000000'
    red:     '0xdd0907'
    green:   '0x1fb714'
    yellow:  '0xfbf305'
    blue:    '0x0000d3'
    magenta: '0x4700a5'
    cyan:    '0x02abea'
    white:   '0xc0c0c0'

  # Bright colors
  bright:
    black:   '0x808080'
    red:     '0xff6403'
    green:   '0x404040'
    yellow:  '0x404040'
    blue:    '0x808080'
    magenta: '0xc0c0c0'
    cyan:    '0x90713a'
    white:   '0xffffff'

draw_bold_text_with_bright_colors: false
