# Base16 Atelier Seaside Light 256 - alacritty color config
# Bram de Haan (http://atelierbramdehaan.nl)
colors:
  # Default colors
  primary:
    background: '0xf4fbf4'
    foreground: '0x5e6e5e'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0xf4fbf4'
    cursor: '0x5e6e5e'

  # Normal colors
  normal:
    black:   '0xf4fbf4'
    red:     '0xe6193c'
    green:   '0x29a329'
    yellow:  '0x98981b'
    blue:    '0x3d62f5'
    magenta: '0xad2bee'
    cyan:    '0x1999b3'
    white:   '0x5e6e5e'

  # Bright colors
  bright:
    black:   '0x809980'
    red:     '0xe6193c'
    green:   '0x29a329'
    yellow:  '0x98981b'
    blue:    '0x3d62f5'
    magenta: '0xad2bee'
    cyan:    '0x1999b3'
    white:   '0x131513'

  indexed_colors:
    - { index: 16, color: '0x87711d' }
    - { index: 17, color: '0xe619c3' }
    - { index: 18, color: '0xcfe8cf' }
    - { index: 19, color: '0x8ca68c' }
    - { index: 20, color: '0x687d68' }
    - { index: 21, color: '0x242924' }
