# Base16 Atelier Dune - alacritty color config
# Bram de Haan (http://atelierbramdehaan.nl)
colors:
  # Default colors
  primary:
    background: '0x20201d'
    foreground: '0xa6a28c'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0x20201d'
    cursor: '0xa6a28c'

  # Normal colors
  normal:
    black:   '0x20201d'
    red:     '0xd73737'
    green:   '0x60ac39'
    yellow:  '0xae9513'
    blue:    '0x6684e1'
    magenta: '0xb854d4'
    cyan:    '0x1fad83'
    white:   '0xa6a28c'

  # Bright colors
  bright:
    black:   '0x7d7a68'
    red:     '0xb65611'
    green:   '0x292824'
    yellow:  '0x6e6b5e'
    blue:    '0x999580'
    magenta: '0xe8e4cf'
    cyan:    '0xd43552'
    white:   '0xfefbec'

draw_bold_text_with_bright_colors: false
