# Base16 Atelier Lakeside Light 256 - alacritty color config
# Bram de Haan (http://atelierbramdehaan.nl)
colors:
  # Default colors
  primary:
    background: '0xebf8ff'
    foreground: '0x516d7b'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0xebf8ff'
    cursor: '0x516d7b'

  # Normal colors
  normal:
    black:   '0xebf8ff'
    red:     '0xd22d72'
    green:   '0x568c3b'
    yellow:  '0x8a8a0f'
    blue:    '0x257fad'
    magenta: '0x6b6bb8'
    cyan:    '0x2d8f6f'
    white:   '0x516d7b'

  # Bright colors
  bright:
    black:   '0x7195a8'
    red:     '0xd22d72'
    green:   '0x568c3b'
    yellow:  '0x8a8a0f'
    blue:    '0x257fad'
    magenta: '0x6b6bb8'
    cyan:    '0x2d8f6f'
    white:   '0x161b1d'

  indexed_colors:
    - { index: 16, color: '0x935c25' }
    - { index: 17, color: '0xb72dd2' }
    - { index: 18, color: '0xc1e4f6' }
    - { index: 19, color: '0x7ea2b4' }
    - { index: 20, color: '0x5a7b8c' }
    - { index: 21, color: '0x1f292e' }
