# Base16 Nord 256 - alacritty color config
# arcticicestudio
colors:
  # Default colors
  primary:
    background: '0x2e3440'
    foreground: '0xe5e9f0'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0x2e3440'
    cursor: '0xe5e9f0'

  # Normal colors
  normal:
    black:   '0x2e3440'
    red:     '0xbf616a'
    green:   '0xa3be8c'
    yellow:  '0xebcb8b'
    blue:    '0x81a1c1'
    magenta: '0xb48ead'
    cyan:    '0x88c0d0'
    white:   '0xe5e9f0'

  # Bright colors
  bright:
    black:   '0x4c566a'
    red:     '0xbf616a'
    green:   '0xa3be8c'
    yellow:  '0xebcb8b'
    blue:    '0x81a1c1'
    magenta: '0xb48ead'
    cyan:    '0x88c0d0'
    white:   '0x8fbcbb'

  indexed_colors:
    - { index: 16, color: '0xd08770' }
    - { index: 17, color: '0x5e81ac' }
    - { index: 18, color: '0x3b4252' }
    - { index: 19, color: '0x434c5e' }
    - { index: 20, color: '0xd8dee9' }
    - { index: 21, color: '0xeceff4' }
