# Base16 Apprentice 256 - alacritty color config
# romainl
colors:
  # Default colors
  primary:
    background: '0x262626'
    foreground: '0xbcbcbc'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0x262626'
    cursor: '0xbcbcbc'

  # Normal colors
  normal:
    black:   '0x262626'
    red:     '0x5f8787'
    green:   '0x87af87'
    yellow:  '0x5f8787'
    blue:    '0xffffaf'
    magenta: '0x87afd7'
    cyan:    '0x5f875f'
    white:   '0xbcbcbc'

  # Bright colors
  bright:
    black:   '0x6c6c6c'
    red:     '0x5f8787'
    green:   '0x87af87'
    yellow:  '0x5f8787'
    blue:    '0xffffaf'
    magenta: '0x87afd7'
    cyan:    '0x5f875f'
    white:   '0xffffff'

  indexed_colors:
    - { index: 16, color: '0xff8700' }
    - { index: 17, color: '0x5f87af' }
    - { index: 18, color: '0x303030' }
    - { index: 19, color: '0x333333' }
    - { index: 20, color: '0x787878' }
    - { index: 21, color: '0xc9c9c9' }
