# Base16 Paraiso - alacritty color config
# Jan T. Sott
colors:
  # Default colors
  primary:
    background: '0x2f1e2e'
    foreground: '0xa39e9b'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0x2f1e2e'
    cursor: '0xa39e9b'

  # Normal colors
  normal:
    black:   '0x2f1e2e'
    red:     '0xef6155'
    green:   '0x48b685'
    yellow:  '0xfec418'
    blue:    '0x06b6ef'
    magenta: '0x815ba4'
    cyan:    '0x5bc4bf'
    white:   '0xa39e9b'

  # Bright colors
  bright:
    black:   '0x776e71'
    red:     '0xf99b15'
    green:   '0x41323f'
    yellow:  '0x4f424c'
    blue:    '0x8d8687'
    magenta: '0xb9b6b0'
    cyan:    '0xe96ba8'
    white:   '0xe7e9db'

draw_bold_text_with_bright_colors: false
