# Base16 Stella 256 - alacritty color config
# Shrimpram
colors:
  # Default colors
  primary:
    background: '0x2b213c'
    foreground: '0x998bad'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0x2b213c'
    cursor: '0x998bad'

  # Normal colors
  normal:
    black:   '0x2b213c'
    red:     '0xc79987'
    green:   '0xacc79b'
    yellow:  '0xc7c691'
    blue:    '0xa5aad4'
    magenta: '0xc594ff'
    cyan:    '0x9bc7bf'
    white:   '0x998bad'

  # Bright colors
  bright:
    black:   '0x655978'
    red:     '0xc79987'
    green:   '0xacc79b'
    yellow:  '0xc7c691'
    blue:    '0xa5aad4'
    magenta: '0xc594ff'
    cyan:    '0x9bc7bf'
    white:   '0xebdcff'

  indexed_colors:
    - { index: 16, color: '0x8865c6' }
    - { index: 17, color: '0xc7ab87' }
    - { index: 18, color: '0x362b48' }
    - { index: 19, color: '0x4d4160' }
    - { index: 20, color: '0x7f7192' }
    - { index: 21, color: '0xb4a5c8' }
