# Base16 Sakura 256 - alacritty color config
# Misterio77 (http://github.com/Misterio77)
colors:
  # Default colors
  primary:
    background: '0xfeedf3'
    foreground: '0x564448'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0xfeedf3'
    cursor: '0x564448'

  # Normal colors
  normal:
    black:   '0xfeedf3'
    red:     '0xdf2d52'
    green:   '0x2e916d'
    yellow:  '0xc29461'
    blue:    '0x006e93'
    magenta: '0x5e2180'
    cyan:    '0x1d8991'
    white:   '0x564448'

  # Bright colors
  bright:
    black:   '0x755f64'
    red:     '0xdf2d52'
    green:   '0x2e916d'
    yellow:  '0xc29461'
    blue:    '0x006e93'
    magenta: '0x5e2180'
    cyan:    '0x1d8991'
    white:   '0x33292b'

  indexed_colors:
    - { index: 16, color: '0xf6661e' }
    - { index: 17, color: '0xba0d35' }
    - { index: 18, color: '0xf8e2e7' }
    - { index: 19, color: '0xe0ccd1' }
    - { index: 20, color: '0x665055' }
    - { index: 21, color: '0x42383a' }
