# Base16 Unikitty Light 256 - alacritty color config
# Josh W Lewis (@joshwlewis)
colors:
  # Default colors
  primary:
    background: '0xffffff'
    foreground: '0x6c696e'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0xffffff'
    cursor: '0x6c696e'

  # Normal colors
  normal:
    black:   '0xffffff'
    red:     '0xd8137f'
    green:   '0x17ad98'
    yellow:  '0xdc8a0e'
    blue:    '0x775dff'
    magenta: '0xaa17e6'
    cyan:    '0x149bda'
    white:   '0x6c696e'

  # Bright colors
  bright:
    black:   '0xa7a5a8'
    red:     '0xd8137f'
    green:   '0x17ad98'
    yellow:  '0xdc8a0e'
    blue:    '0x775dff'
    magenta: '0xaa17e6'
    cyan:    '0x149bda'
    white:   '0x322d34'

  indexed_colors:
    - { index: 16, color: '0xd65407' }
    - { index: 17, color: '0xe013d0' }
    - { index: 18, color: '0xe1e1e2' }
    - { index: 19, color: '0xc4c3c5' }
    - { index: 20, color: '0x89878b' }
    - { index: 21, color: '0x4f4b51' }
