# Base16 Materia 256 - alacritty color config
# Defman21
colors:
  # Default colors
  primary:
    background: '0x263238'
    foreground: '0xcdd3de'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0x263238'
    cursor: '0xcdd3de'

  # Normal colors
  normal:
    black:   '0x263238'
    red:     '0xec5f67'
    green:   '0x8bd649'
    yellow:  '0xffcc00'
    blue:    '0x89ddff'
    magenta: '0x82aaff'
    cyan:    '0x80cbc4'
    white:   '0xcdd3de'

  # Bright colors
  bright:
    black:   '0x707880'
    red:     '0xec5f67'
    green:   '0x8bd649'
    yellow:  '0xffcc00'
    blue:    '0x89ddff'
    magenta: '0x82aaff'
    cyan:    '0x80cbc4'
    white:   '0xffffff'

  indexed_colors:
    - { index: 16, color: '0xea9560' }
    - { index: 17, color: '0xec5f67' }
    - { index: 18, color: '0x2c393f' }
    - { index: 19, color: '0x37474f' }
    - { index: 20, color: '0xc9ccd3' }
    - { index: 21, color: '0xd5dbe5' }
