# Base16 Silk Light 256 - alacritty color config
# Gabriel Fontes (https://github.com/Misterio77)
colors:
  # Default colors
  primary:
    background: '0xe9f1ef'
    foreground: '0x385156'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0xe9f1ef'
    cursor: '0x385156'

  # Normal colors
  normal:
    black:   '0xe9f1ef'
    red:     '0xcf432e'
    green:   '0x6ca38c'
    yellow:  '0xcfad25'
    blue:    '0x39aac9'
    magenta: '0x6e6582'
    cyan:    '0x329ca2'
    white:   '0x385156'

  # Bright colors
  bright:
    black:   '0x5c787b'
    red:     '0xcf432e'
    green:   '0x6ca38c'
    yellow:  '0xcfad25'
    blue:    '0x39aac9'
    magenta: '0x6e6582'
    cyan:    '0x329ca2'
    white:   '0xd2faff'

  indexed_colors:
    - { index: 16, color: '0xd27f46' }
    - { index: 17, color: '0x865369' }
    - { index: 18, color: '0xccd4d3' }
    - { index: 19, color: '0x90b7b6' }
    - { index: 20, color: '0x4b5b5f' }
    - { index: 21, color: '0x0e3c46' }
