# Base16 Atelier Plateau Light - alacritty color config
# Bram de Haan (http://atelierbramdehaan.nl)
colors:
  # Default colors
  primary:
    background: '0xf4ecec'
    foreground: '0x585050'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0xf4ecec'
    cursor: '0x585050'

  # Normal colors
  normal:
    black:   '0xf4ecec'
    red:     '0xca4949'
    green:   '0x4b8b8b'
    yellow:  '0xa06e3b'
    blue:    '0x7272ca'
    magenta: '0x8464c4'
    cyan:    '0x5485b6'
    white:   '0x585050'

  # Bright colors
  bright:
    black:   '0x7e7777'
    red:     '0xb45a3c'
    green:   '0xe7dfdf'
    yellow:  '0x8a8585'
    blue:    '0x655d5d'
    magenta: '0x292424'
    cyan:    '0xbd5187'
    white:   '0x1b1818'

draw_bold_text_with_bright_colors: false
