# Base16 Da One Black - alacritty color config
# NNB (https://github.com/NNBnh)
colors:
  # Default colors
  primary:
    background: '0x000000'
    foreground: '0xffffff'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0x000000'
    cursor: '0xffffff'

  # Normal colors
  normal:
    black:   '0x000000'
    red:     '0xfa7883'
    green:   '0x98c379'
    yellow:  '0xff9470'
    blue:    '0x6bb8ff'
    magenta: '0xe799ff'
    cyan:    '0x8af5ff'
    white:   '0xffffff'

  # Bright colors
  bright:
    black:   '0x888888'
    red:     '0xffc387'
    green:   '0x282828'
    yellow:  '0x585858'
    blue:    '0xc8c8c8'
    magenta: '0xffffff'
    cyan:    '0xb3684f'
    white:   '0xffffff'

draw_bold_text_with_bright_colors: false
