# Base16 Espresso 256 - alacritty color config
# Unknown. Maintained by Alex Mirrington (https://github.com/alexmirrington)
colors:
  # Default colors
  primary:
    background: '0x2d2d2d'
    foreground: '0xcccccc'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0x2d2d2d'
    cursor: '0xcccccc'

  # Normal colors
  normal:
    black:   '0x2d2d2d'
    red:     '0xd25252'
    green:   '0xa5c261'
    yellow:  '0xffc66d'
    blue:    '0x6c99bb'
    magenta: '0xd197d9'
    cyan:    '0xbed6ff'
    white:   '0xcccccc'

  # Bright colors
  bright:
    black:   '0x777777'
    red:     '0xd25252'
    green:   '0xa5c261'
    yellow:  '0xffc66d'
    blue:    '0x6c99bb'
    magenta: '0xd197d9'
    cyan:    '0xbed6ff'
    white:   '0xffffff'

  indexed_colors:
    - { index: 16, color: '0xf9a959' }
    - { index: 17, color: '0xf97394' }
    - { index: 18, color: '0x393939' }
    - { index: 19, color: '0x515151' }
    - { index: 20, color: '0xb4b7b4' }
    - { index: 21, color: '0xe0e0e0' }
