# Base16 Atelier Seaside Light - alacritty color config
# Bram de Haan (http://atelierbramdehaan.nl)
colors:
  # Default colors
  primary:
    background: '0xf4fbf4'
    foreground: '0x5e6e5e'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0xf4fbf4'
    cursor: '0x5e6e5e'

  # Normal colors
  normal:
    black:   '0xf4fbf4'
    red:     '0xe6193c'
    green:   '0x29a329'
    yellow:  '0x98981b'
    blue:    '0x3d62f5'
    magenta: '0xad2bee'
    cyan:    '0x1999b3'
    white:   '0x5e6e5e'

  # Bright colors
  bright:
    black:   '0x809980'
    red:     '0x87711d'
    green:   '0xcfe8cf'
    yellow:  '0x8ca68c'
    blue:    '0x687d68'
    magenta: '0x242924'
    cyan:    '0xe619c3'
    white:   '0x131513'

draw_bold_text_with_bright_colors: false
