# Base16 Marrakesh - alacritty color config
# Alexandre Gavioli (http://github.com/Alexx2/)
colors:
  # Default colors
  primary:
    background: '0x201602'
    foreground: '0x948e48'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0x201602'
    cursor: '0x948e48'

  # Normal colors
  normal:
    black:   '0x201602'
    red:     '0xc35359'
    green:   '0x18974e'
    yellow:  '0xa88339'
    blue:    '0x477ca1'
    magenta: '0x8868b3'
    cyan:    '0x75a738'
    white:   '0x948e48'

  # Bright colors
  bright:
    black:   '0x6c6823'
    red:     '0xb36144'
    green:   '0x302e00'
    yellow:  '0x5f5b17'
    blue:    '0x86813b'
    magenta: '0xccc37a'
    cyan:    '0xb3588e'
    white:   '0xfaf0a5'

draw_bold_text_with_bright_colors: false
