# Base16 Material Vivid 256 - alacritty color config
# joshyrobot
colors:
  # Default colors
  primary:
    background: '0x202124'
    foreground: '0x80868b'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0x202124'
    cursor: '0x80868b'

  # Normal colors
  normal:
    black:   '0x202124'
    red:     '0xf44336'
    green:   '0x00e676'
    yellow:  '0xffeb3b'
    blue:    '0x2196f3'
    magenta: '0x673ab7'
    cyan:    '0x00bcd4'
    white:   '0x80868b'

  # Bright colors
  bright:
    black:   '0x44464d'
    red:     '0xf44336'
    green:   '0x00e676'
    yellow:  '0xffeb3b'
    blue:    '0x2196f3'
    magenta: '0x673ab7'
    cyan:    '0x00bcd4'
    white:   '0xffffff'

  indexed_colors:
    - { index: 16, color: '0xff9800' }
    - { index: 17, color: '0x8d6e63' }
    - { index: 18, color: '0x27292c' }
    - { index: 19, color: '0x323639' }
    - { index: 20, color: '0x676c71' }
    - { index: 21, color: '0x9e9e9e' }
