# Base16 Brewer - alacritty color config
# Timothée Poisot (http://github.com/tpoisot)
colors:
  # Default colors
  primary:
    background: '0x0c0d0e'
    foreground: '0xb7b8b9'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0x0c0d0e'
    cursor: '0xb7b8b9'

  # Normal colors
  normal:
    black:   '0x0c0d0e'
    red:     '0xe31a1c'
    green:   '0x31a354'
    yellow:  '0xdca060'
    blue:    '0x3182bd'
    magenta: '0x756bb1'
    cyan:    '0x80b1d3'
    white:   '0xb7b8b9'

  # Bright colors
  bright:
    black:   '0x737475'
    red:     '0xe6550d'
    green:   '0x2e2f30'
    yellow:  '0x515253'
    blue:    '0x959697'
    magenta: '0xdadbdc'
    cyan:    '0xb15928'
    white:   '0xfcfdfe'

draw_bold_text_with_bright_colors: false
