# Base16 Material Lighter - alacritty color config
# Nate Peterson
colors:
  # Default colors
  primary:
    background: '0xfafafa'
    foreground: '0x80cbc4'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0xfafafa'
    cursor: '0x80cbc4'

  # Normal colors
  normal:
    black:   '0xfafafa'
    red:     '0xff5370'
    green:   '0x91b859'
    yellow:  '0xffb62c'
    blue:    '0x6182b8'
    magenta: '0x7c4dff'
    cyan:    '0x39adb5'
    white:   '0x80cbc4'

  # Bright colors
  bright:
    black:   '0xccd7da'
    red:     '0xf76d47'
    green:   '0xe7eaec'
    yellow:  '0xcceae7'
    blue:    '0x8796b0'
    magenta: '0x80cbc4'
    cyan:    '0xe53935'
    white:   '0xffffff'

draw_bold_text_with_bright_colors: false
