# Base16 Da One Gray 256 - alacritty color config
# NNB (https://github.com/NNBnh)
colors:
  # Default colors
  primary:
    background: '0x181818'
    foreground: '0xffffff'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0x181818'
    cursor: '0xffffff'

  # Normal colors
  normal:
    black:   '0x181818'
    red:     '0xfa7883'
    green:   '0x98c379'
    yellow:  '0xff9470'
    blue:    '0x6bb8ff'
    magenta: '0xe799ff'
    cyan:    '0x8af5ff'
    white:   '0xffffff'

  # Bright colors
  bright:
    black:   '0x888888'
    red:     '0xfa7883'
    green:   '0x98c379'
    yellow:  '0xff9470'
    blue:    '0x6bb8ff'
    magenta: '0xe799ff'
    cyan:    '0x8af5ff'
    white:   '0xffffff'

  indexed_colors:
    - { index: 16, color: '0xffc387' }
    - { index: 17, color: '0xb3684f' }
    - { index: 18, color: '0x282828' }
    - { index: 19, color: '0x585858' }
    - { index: 20, color: '0xc8c8c8' }
    - { index: 21, color: '0xffffff' }
