# Base16 Fruit Soda 256 - alacritty color config
# jozip
colors:
  # Default colors
  primary:
    background: '0xf1ecf1'
    foreground: '0x515151'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0xf1ecf1'
    cursor: '0x515151'

  # Normal colors
  normal:
    black:   '0xf1ecf1'
    red:     '0xfe3e31'
    green:   '0x47f74c'
    yellow:  '0xf7e203'
    blue:    '0x2931df'
    magenta: '0x611fce'
    cyan:    '0x0f9cfd'
    white:   '0x515151'

  # Bright colors
  bright:
    black:   '0xb5b4b6'
    red:     '0xfe3e31'
    green:   '0x47f74c'
    yellow:  '0xf7e203'
    blue:    '0x2931df'
    magenta: '0x611fce'
    cyan:    '0x0f9cfd'
    white:   '0x2d2c2c'

  indexed_colors:
    - { index: 16, color: '0xfe6d08' }
    - { index: 17, color: '0xb16f40' }
    - { index: 18, color: '0xe0dee0' }
    - { index: 19, color: '0xd8d5d5' }
    - { index: 20, color: '0x979598' }
    - { index: 21, color: '0x474545' }
