# Base16 Windows NT 256 - alacritty color config
# Fergus Collins (https://github.com/C-Fergus)
colors:
  # Default colors
  primary:
    background: '0x000000'
    foreground: '0xc0c0c0'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0x000000'
    cursor: '0xc0c0c0'

  # Normal colors
  normal:
    black:   '0x000000'
    red:     '0xff0000'
    green:   '0x00ff00'
    yellow:  '0xffff00'
    blue:    '0x0000ff'
    magenta: '0xff00ff'
    cyan:    '0x00ffff'
    white:   '0xc0c0c0'

  # Bright colors
  bright:
    black:   '0x808080'
    red:     '0xff0000'
    green:   '0x00ff00'
    yellow:  '0xffff00'
    blue:    '0x0000ff'
    magenta: '0xff00ff'
    cyan:    '0x00ffff'
    white:   '0xffffff'

  indexed_colors:
    - { index: 16, color: '0x808000' }
    - { index: 17, color: '0x008000' }
    - { index: 18, color: '0x2a2a2a' }
    - { index: 19, color: '0x555555' }
    - { index: 20, color: '0xa1a1a1' }
    - { index: 21, color: '0xe0e0e0' }
