# Base16 selenized-light 256 - alacritty color config
# Jan Warchol (https://github.com/jan-warchol/selenized) / adapted to base16 by ali
colors:
  # Default colors
  primary:
    background: '0xfbf3db'
    foreground: '0x53676d'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0xfbf3db'
    cursor: '0x53676d'

  # Normal colors
  normal:
    black:   '0xfbf3db'
    red:     '0xcc1729'
    green:   '0x428b00'
    yellow:  '0xa78300'
    blue:    '0x006dce'
    magenta: '0x825dc0'
    cyan:    '0x00978a'
    white:   '0x53676d'

  # Bright colors
  bright:
    black:   '0x909995'
    red:     '0xcc1729'
    green:   '0x428b00'
    yellow:  '0xa78300'
    blue:    '0x006dce'
    magenta: '0x825dc0'
    cyan:    '0x00978a'
    white:   '0x3a4d53'

  indexed_colors:
    - { index: 16, color: '0xbc5819' }
    - { index: 17, color: '0xc44392' }
    - { index: 18, color: '0xece3cc' }
    - { index: 19, color: '0xd5cdb6' }
    - { index: 20, color: '0x909995' }
    - { index: 21, color: '0x3a4d53' }
