# Base16 Equilibrium Gray Dark 256 - alacritty color config
# Carlo Abelli
colors:
  # Default colors
  primary:
    background: '0x111111'
    foreground: '0xababab'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0x111111'
    cursor: '0xababab'

  # Normal colors
  normal:
    black:   '0x111111'
    red:     '0xf04339'
    green:   '0x7f8b00'
    yellow:  '0xbb8801'
    blue:    '0x008dd1'
    magenta: '0x6a7fd2'
    cyan:    '0x00948b'
    white:   '0xababab'

  # Bright colors
  bright:
    black:   '0x777777'
    red:     '0xf04339'
    green:   '0x7f8b00'
    yellow:  '0xbb8801'
    blue:    '0x008dd1'
    magenta: '0x6a7fd2'
    cyan:    '0x00948b'
    white:   '0xe2e2e2'

  indexed_colors:
    - { index: 16, color: '0xdf5923' }
    - { index: 17, color: '0xe3488e' }
    - { index: 18, color: '0x1b1b1b' }
    - { index: 19, color: '0x262626' }
    - { index: 20, color: '0x919191' }
    - { index: 21, color: '0xc6c6c6' }
