# Base16 Edge Light 256 - alacritty color config
# cjayross (https://github.com/cjayross)
colors:
  # Default colors
  primary:
    background: '0xfafafa'
    foreground: '0x5e646f'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0xfafafa'
    cursor: '0x5e646f'

  # Normal colors
  normal:
    black:   '0xfafafa'
    red:     '0xdb7070'
    green:   '0x7c9f4b'
    yellow:  '0xd69822'
    blue:    '0x6587bf'
    magenta: '0xb870ce'
    cyan:    '0x509c93'
    white:   '0x5e646f'

  # Bright colors
  bright:
    black:   '0x5e646f'
    red:     '0xdb7070'
    green:   '0x7c9f4b'
    yellow:  '0xd69822'
    blue:    '0x6587bf'
    magenta: '0xb870ce'
    cyan:    '0x509c93'
    white:   '0x5e646f'

  indexed_colors:
    - { index: 16, color: '0xdb7070' }
    - { index: 17, color: '0x509c93' }
    - { index: 18, color: '0x7c9f4b' }
    - { index: 19, color: '0xd69822' }
    - { index: 20, color: '0x6587bf' }
    - { index: 21, color: '0xb870ce' }
