# Base16 Da One White 256 - alacritty color config
# NNB (https://github.com/NNBnh)
colors:
  # Default colors
  primary:
    background: '0xffffff'
    foreground: '0x181818'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0xffffff'
    cursor: '0x181818'

  # Normal colors
  normal:
    black:   '0xffffff'
    red:     '0xde5d6e'
    green:   '0x76a85d'
    yellow:  '0xb3684f'
    blue:    '0x5890f8'
    magenta: '0xc173d1'
    cyan:    '0x64b5a7'
    white:   '0x181818'

  # Bright colors
  bright:
    black:   '0x585858'
    red:     '0xde5d6e'
    green:   '0x76a85d'
    yellow:  '0xb3684f'
    blue:    '0x5890f8'
    magenta: '0xc173d1'
    cyan:    '0x64b5a7'
    white:   '0x000000'

  indexed_colors:
    - { index: 16, color: '0xff9470' }
    - { index: 17, color: '0xb3684f' }
    - { index: 18, color: '0xc8c8c8' }
    - { index: 19, color: '0x888888' }
    - { index: 20, color: '0x282828' }
    - { index: 21, color: '0x000000' }
