# Base16 Summerfruit Light 256 - alacritty color config
# Christopher Corley (http://christop.club/)
colors:
  # Default colors
  primary:
    background: '0xffffff'
    foreground: '0x101010'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0xffffff'
    cursor: '0x101010'

  # Normal colors
  normal:
    black:   '0xffffff'
    red:     '0xff0086'
    green:   '0x00c918'
    yellow:  '0xaba800'
    blue:    '0x3777e6'
    magenta: '0xad00a1'
    cyan:    '0x1faaaa'
    white:   '0x101010'

  # Bright colors
  bright:
    black:   '0xb0b0b0'
    red:     '0xff0086'
    green:   '0x00c918'
    yellow:  '0xaba800'
    blue:    '0x3777e6'
    magenta: '0xad00a1'
    cyan:    '0x1faaaa'
    white:   '0x202020'

  indexed_colors:
    - { index: 16, color: '0xfd8900' }
    - { index: 17, color: '0xcc6633' }
    - { index: 18, color: '0xe0e0e0' }
    - { index: 19, color: '0xd0d0d0' }
    - { index: 20, color: '0x000000' }
    - { index: 21, color: '0x151515' }
