# Base16 Atlas - alacritty color config
# Alex Lende (https://ajlende.com)
colors:
  # Default colors
  primary:
    background: '0x002635'
    foreground: '0xa1a19a'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0x002635'
    cursor: '0xa1a19a'

  # Normal colors
  normal:
    black:   '0x002635'
    red:     '0xff5a67'
    green:   '0x7fc06e'
    yellow:  '0xffcc1b'
    blue:    '0x5dd7b9'
    magenta: '0x9a70a4'
    cyan:    '0x14747e'
    white:   '0xa1a19a'

  # Bright colors
  bright:
    black:   '0x6c8b91'
    red:     '0xf08e48'
    green:   '0x00384d'
    yellow:  '0x517f8d'
    blue:    '0x869696'
    magenta: '0xe6e6dc'
    cyan:    '0xc43060'
    white:   '0xfafaf8'

draw_bold_text_with_bright_colors: false
