# Base16 Brogrammer 256 - alacritty color config
# Vik Ramanujam (http://github.com/piggyslasher)
colors:
  # Default colors
  primary:
    background: '0x1f1f1f'
    foreground: '0x4e5ab7'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0x1f1f1f'
    cursor: '0x4e5ab7'

  # Normal colors
  normal:
    black:   '0x1f1f1f'
    red:     '0xd6dbe5'
    green:   '0xf3bd09'
    yellow:  '0x1dd361'
    blue:    '0x5350b9'
    magenta: '0x0f7ddb'
    cyan:    '0x1081d6'
    white:   '0x4e5ab7'

  # Bright colors
  bright:
    black:   '0xecba0f'
    red:     '0xd6dbe5'
    green:   '0xf3bd09'
    yellow:  '0x1dd361'
    blue:    '0x5350b9'
    magenta: '0x0f7ddb'
    cyan:    '0x1081d6'
    white:   '0xd6dbe5'

  indexed_colors:
    - { index: 16, color: '0xde352e' }
    - { index: 17, color: '0xffffff' }
    - { index: 18, color: '0xf81118' }
    - { index: 19, color: '0x2dc55e' }
    - { index: 20, color: '0x2a84d2' }
    - { index: 21, color: '0x1081d6' }
