# Base16 London Tube 256 - alacritty color config
# Jan T. Sott
colors:
  # Default colors
  primary:
    background: '0x231f20'
    foreground: '0xd9d8d8'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0x231f20'
    cursor: '0xd9d8d8'

  # Normal colors
  normal:
    black:   '0x231f20'
    red:     '0xee2e24'
    green:   '0x00853e'
    yellow:  '0xffd204'
    blue:    '0x009ddc'
    magenta: '0x98005d'
    cyan:    '0x85cebc'
    white:   '0xd9d8d8'

  # Bright colors
  bright:
    black:   '0x737171'
    red:     '0xee2e24'
    green:   '0x00853e'
    yellow:  '0xffd204'
    blue:    '0x009ddc'
    magenta: '0x98005d'
    cyan:    '0x85cebc'
    white:   '0xffffff'

  indexed_colors:
    - { index: 16, color: '0xf386a1' }
    - { index: 17, color: '0xb06110' }
    - { index: 18, color: '0x1c3f95' }
    - { index: 19, color: '0x5a5758' }
    - { index: 20, color: '0x959ca1' }
    - { index: 21, color: '0xe7e7e8' }
