# Base16 Porple - alacritty color config
# Niek den Breeje (https://github.com/AuditeMarlow)
colors:
  # Default colors
  primary:
    background: '0x292c36'
    foreground: '0xd8d8d8'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0x292c36'
    cursor: '0xd8d8d8'

  # Normal colors
  normal:
    black:   '0x292c36'
    red:     '0xf84547'
    green:   '0x95c76f'
    yellow:  '0xefa16b'
    blue:    '0x8485ce'
    magenta: '0xb74989'
    cyan:    '0x64878f'
    white:   '0xd8d8d8'

  # Bright colors
  bright:
    black:   '0x65568a'
    red:     '0xd28e5d'
    green:   '0x333344'
    yellow:  '0x474160'
    blue:    '0xb8b8b8'
    magenta: '0xe8e8e8'
    cyan:    '0x986841'
    white:   '0xf8f8f8'

draw_bold_text_with_bright_colors: false
