# Base16 Windows 10 - alacritty color config
# Fergus Collins (https://github.com/C-Fergus)
colors:
  # Default colors
  primary:
    background: '0x0c0c0c'
    foreground: '0xcccccc'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0x0c0c0c'
    cursor: '0xcccccc'

  # Normal colors
  normal:
    black:   '0x0c0c0c'
    red:     '0xe74856'
    green:   '0x16c60c'
    yellow:  '0xf9f1a5'
    blue:    '0x3b78ff'
    magenta: '0xb4009e'
    cyan:    '0x61d6d6'
    white:   '0xcccccc'

  # Bright colors
  bright:
    black:   '0x767676'
    red:     '0xc19c00'
    green:   '0x2f2f2f'
    yellow:  '0x535353'
    blue:    '0xb9b9b9'
    magenta: '0xdfdfdf'
    cyan:    '0x13a10e'
    white:   '0xf2f2f2'

draw_bold_text_with_bright_colors: false
