# Base16 emil 256 - alacritty color config
# limelier
colors:
  # Default colors
  primary:
    background: '0xefefef'
    foreground: '0x313145'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0xefefef'
    cursor: '0x313145'

  # Normal colors
  normal:
    black:   '0xefefef'
    red:     '0xf43979'
    green:   '0x0073a8'
    yellow:  '0xff669b'
    blue:    '0x471397'
    magenta: '0x6916b6'
    cyan:    '0x2155d6'
    white:   '0x313145'

  # Bright colors
  bright:
    black:   '0x7c7c98'
    red:     '0xf43979'
    green:   '0x0073a8'
    yellow:  '0xff669b'
    blue:    '0x471397'
    magenta: '0x6916b6'
    cyan:    '0x2155d6'
    white:   '0x1a1a2f'

  indexed_colors:
    - { index: 16, color: '0xd22a8b' }
    - { index: 17, color: '0x8d17a5' }
    - { index: 18, color: '0xbebed2' }
    - { index: 19, color: '0x9e9eaf' }
    - { index: 20, color: '0x505063' }
    - { index: 21, color: '0x22223a' }
