# Base16 Windows 95 Light - alacritty color config
# Fergus Collins (https://github.com/C-Fergus)
colors:
  # Default colors
  primary:
    background: '0xfcfcfc'
    foreground: '0x545454'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0xfcfcfc'
    cursor: '0x545454'

  # Normal colors
  normal:
    black:   '0xfcfcfc'
    red:     '0xa80000'
    green:   '0x00a800'
    yellow:  '0xa85400'
    blue:    '0x0000a8'
    magenta: '0xa800a8'
    cyan:    '0x00a8a8'
    white:   '0x545454'

  # Bright colors
  bright:
    black:   '0xa8a8a8'
    red:     '0xfcfc54'
    green:   '0xe0e0e0'
    yellow:  '0xc4c4c4'
    blue:    '0x7e7e7e'
    magenta: '0x2a2a2a'
    cyan:    '0x54fc54'
    white:   '0x000000'

draw_bold_text_with_bright_colors: false
