# Base16 Embers - alacritty color config
# Jannik Siebert (https://github.com/janniks)
colors:
  # Default colors
  primary:
    background: '0x16130f'
    foreground: '0xa39a90'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0x16130f'
    cursor: '0xa39a90'

  # Normal colors
  normal:
    black:   '0x16130f'
    red:     '0x826d57'
    green:   '0x57826d'
    yellow:  '0x6d8257'
    blue:    '0x6d5782'
    magenta: '0x82576d'
    cyan:    '0x576d82'
    white:   '0xa39a90'

  # Bright colors
  bright:
    black:   '0x5a5047'
    red:     '0x828257'
    green:   '0x2c2620'
    yellow:  '0x433b32'
    blue:    '0x8a8075'
    magenta: '0xbeb6ae'
    cyan:    '0x825757'
    white:   '0xdbd6d1'

draw_bold_text_with_bright_colors: false
