# Base16 Pop 256 - alacritty color config
# Chris Kempson (http://chriskempson.com)
colors:
  # Default colors
  primary:
    background: '0x000000'
    foreground: '0xd0d0d0'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0x000000'
    cursor: '0xd0d0d0'

  # Normal colors
  normal:
    black:   '0x000000'
    red:     '0xeb008a'
    green:   '0x37b349'
    yellow:  '0xf8ca12'
    blue:    '0x0e5a94'
    magenta: '0xb31e8d'
    cyan:    '0x00aabb'
    white:   '0xd0d0d0'

  # Bright colors
  bright:
    black:   '0x505050'
    red:     '0xeb008a'
    green:   '0x37b349'
    yellow:  '0xf8ca12'
    blue:    '0x0e5a94'
    magenta: '0xb31e8d'
    cyan:    '0x00aabb'
    white:   '0xffffff'

  indexed_colors:
    - { index: 16, color: '0xf29333' }
    - { index: 17, color: '0x7a2d00' }
    - { index: 18, color: '0x202020' }
    - { index: 19, color: '0x303030' }
    - { index: 20, color: '0xb0b0b0' }
    - { index: 21, color: '0xe0e0e0' }
