# Base16 Woodland 256 - alacritty color config
# Jay Cornwall (https://jcornwall.com)
colors:
  # Default colors
  primary:
    background: '0x231e18'
    foreground: '0xcabcb1'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0x231e18'
    cursor: '0xcabcb1'

  # Normal colors
  normal:
    black:   '0x231e18'
    red:     '0xd35c5c'
    green:   '0xb7ba53'
    yellow:  '0xe0ac16'
    blue:    '0x88a4d3'
    magenta: '0xbb90e2'
    cyan:    '0x6eb958'
    white:   '0xcabcb1'

  # Bright colors
  bright:
    black:   '0x9d8b70'
    red:     '0xd35c5c'
    green:   '0xb7ba53'
    yellow:  '0xe0ac16'
    blue:    '0x88a4d3'
    magenta: '0xbb90e2'
    cyan:    '0x6eb958'
    white:   '0xe4d4c8'

  indexed_colors:
    - { index: 16, color: '0xca7f32' }
    - { index: 17, color: '0xb49368' }
    - { index: 18, color: '0x302b25' }
    - { index: 19, color: '0x48413a' }
    - { index: 20, color: '0xb4a490' }
    - { index: 21, color: '0xd7c8bc' }
