# Base16 Atelier Heath 256 - alacritty color config
# Bram de Haan (http://atelierbramdehaan.nl)
colors:
  # Default colors
  primary:
    background: '0x1b181b'
    foreground: '0xab9bab'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0x1b181b'
    cursor: '0xab9bab'

  # Normal colors
  normal:
    black:   '0x1b181b'
    red:     '0xca402b'
    green:   '0x918b3b'
    yellow:  '0xbb8a35'
    blue:    '0x516aec'
    magenta: '0x7b59c0'
    cyan:    '0x159393'
    white:   '0xab9bab'

  # Bright colors
  bright:
    black:   '0x776977'
    red:     '0xca402b'
    green:   '0x918b3b'
    yellow:  '0xbb8a35'
    blue:    '0x516aec'
    magenta: '0x7b59c0'
    cyan:    '0x159393'
    white:   '0xf7f3f7'

  indexed_colors:
    - { index: 16, color: '0xa65926' }
    - { index: 17, color: '0xcc33cc' }
    - { index: 18, color: '0x292329' }
    - { index: 19, color: '0x695d69' }
    - { index: 20, color: '0x9e8f9e' }
    - { index: 21, color: '0xd8cad8' }
