# Base16 Green Screen 256 - alacritty color config
# Chris Kempson (http://chriskempson.com)
colors:
  # Default colors
  primary:
    background: '0x001100'
    foreground: '0x00bb00'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0x001100'
    cursor: '0x00bb00'

  # Normal colors
  normal:
    black:   '0x001100'
    red:     '0x007700'
    green:   '0x00bb00'
    yellow:  '0x007700'
    blue:    '0x009900'
    magenta: '0x00bb00'
    cyan:    '0x005500'
    white:   '0x00bb00'

  # Bright colors
  bright:
    black:   '0x007700'
    red:     '0x007700'
    green:   '0x00bb00'
    yellow:  '0x007700'
    blue:    '0x009900'
    magenta: '0x00bb00'
    cyan:    '0x005500'
    white:   '0x00ff00'

  indexed_colors:
    - { index: 16, color: '0x009900' }
    - { index: 17, color: '0x005500' }
    - { index: 18, color: '0x003300' }
    - { index: 19, color: '0x005500' }
    - { index: 20, color: '0x009900' }
    - { index: 21, color: '0x00dd00' }
