# Base16 Humanoid light 256 - alacritty color config
# Thomas (tasmo) Friese
colors:
  # Default colors
  primary:
    background: '0xf8f8f2'
    foreground: '0x232629'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0xf8f8f2'
    cursor: '0x232629'

  # Normal colors
  normal:
    black:   '0xf8f8f2'
    red:     '0xb0151a'
    green:   '0x388e3c'
    yellow:  '0xffb627'
    blue:    '0x0082c9'
    magenta: '0x700f98'
    cyan:    '0x008e8e'
    white:   '0x232629'

  # Bright colors
  bright:
    black:   '0xc0c0bd'
    red:     '0xb0151a'
    green:   '0x388e3c'
    yellow:  '0xffb627'
    blue:    '0x0082c9'
    magenta: '0x700f98'
    cyan:    '0x008e8e'
    white:   '0x070708'

  indexed_colors:
    - { index: 16, color: '0xff3d00' }
    - { index: 17, color: '0xb27701' }
    - { index: 18, color: '0xefefe9' }
    - { index: 19, color: '0xdeded8' }
    - { index: 20, color: '0x60615d' }
    - { index: 21, color: '0x2f3337' }
